import {persistence} from './persistence.js';
import {exportMapImage} from './export-image.js';
import {WorldMap} from './map.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],C=window.AtlasCore,turf=window.turf;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const populationText=v=>v==null?'—':num(v/(v>=1e8?1e8:10000))+(v>=1e8?' 亿人':' 万人');
const totalsSwitch=c=>`<label class="full check-label"><input name="includeInNationalTotals" type="checkbox" ${C.countsInNationalTotals(c)?'checked':''}>计入国内总数（人口、GDP 与城市数量）</label>`;
const num=v=>Number(v).toLocaleString('zh-CN',{maximumFractionDigits:1});
let state={version:1,territories:[],cities:[],seaLevel:3.7,seaYear:2025,seaScenario:{baselineYear:1986,baselineLevel:0,referenceYear:2025,referenceLevel:3.7,annualRate:3.7/39,method:'linear'},mode:'surface',customDem:null,adminExtras:[]},selection='song',tab='countries',gazetteer=[],baseAdmin=null,history=new C.History(15),editBefore=null,saveTimer=null,saveQueue=Promise.resolve(),dirty=false,revision=0,modalSubmit=null,loadCompleted=false;
const map=new WorldMap($('#map'),{
 select:entity=>select(entity.properties?.id||entity.id),hover:showHover,coordinates:showCoordinates,zoom:k=>$('#zoomLabel').textContent=Math.round(k*100)+'%',
 beginEdit:()=>{editBefore=C.clone(state);},cancelEdit:()=>{if(editBefore){state=editBefore;editBefore=null;sync();}},
 moveVertex:(from,to)=>{map.invalidateGeometry();C.moveShared(state.territories,from,to);map.update(state.territories,state.cities);},
 moveCity:(id,ll)=>{const c=state.cities.find(c=>c.id===id);c.coordinates=ll.map(v=>+v.toFixed(6));c.elevation=null;c.elevationSource='移动后待重新查询';selection=id;map.selected=id;},
 endEdit:()=>{if(editBefore){try{const changed=selectedFeature();if(changed&&map.tool==='vertices'&&turf.kinks(changed).features.length)throw Error('边界自交，已恢复拖动前的位置');history.push(editBefore);editBefore=null;changedState();}catch(e){state=editBefore;editBefore=null;sync();toast(e.message);}}},
 vertexSelected:p=>editVertexCoordinates(p),removeVertex:p=>transaction('删除边界顶点',()=>{if(!C.removeShared(state.territories,p))throw Error('无法删除：多边形至少保留 3 个顶点');}),
 addVertex:(a,b,p)=>transaction('插入边界顶点',()=>C.insertShared(state.territories,a,b,p)),
 addCity:ll=>cityForm(null,ll),placeCity:ll=>{const c=selectedCity();if(c)transaction('移动城市',()=>{c.coordinates=ll;c.elevation=null;c.elevationSource='移动后待查询';});setTool('select');},
 assign:assignRegion,finishDraw, error:m=>toast('地形计算失败：'+m)
});
window.atlas={get state(){return state;},map,get selection(){return selection;}};
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4600);}
function status(message){$('#statusText').textContent=message;}
function selectedFeature(){return state.territories.find(f=>f.properties.id===selection);}
function selectedCity(){return state.cities.find(c=>c.id===selection);}
function countryOptions(current='',allowEmpty=true){return (allowEmpty?'<option value="">未指定</option>':'')+state.territories.sort((a,b)=>a.properties.name.localeCompare(b.properties.name,'zh')).map(f=>`<option value="${esc(f.properties.id)}" ${f.properties.id===current?'selected':''}>${esc(f.properties.name)}</option>`).join('');}
function sync(){map.layers.water=state.showWater!==false;$('#layerWater').checked=map.layers.water;map.showCountryNames=state.showCountryNames!==false;$('#showCountryNames').checked=map.showCountryNames;map.showFeatured=state.showFeatured!==false;$('#showFeatured').checked=map.showFeatured;map.palette=state.palette||'atlas';$('#palette').value=map.palette;applyTheme(state.theme||'light');renderPalette();map.coastMode=state.coastMode||'illustrated';$('#coastMode').value=map.coastMode;map.selected=selection;map.countryNameLanguages=state.countryNameLanguages||{zh:true,en:true,local:true};for(const [key,id] of [['zh','countryLangZh'],['en','countryLangEn'],['local','countryLangLocal']])$('#'+id).checked=map.countryNameLanguages[key];map.nameLanguages=state.nameLanguages||{zh:true,en:true,local:true};for(const [key,id] of [['zh','langZh'],['en','langEn'],['local','langLocal']])$('#'+id).checked=map.nameLanguages[key];map.sea=state.seaLevel;map.mode=state.mode;map.update(state.territories,state.cities);renderList();renderDetails();updateSeaUI();$('#undoBtn').disabled=!history.past.length;$('#redoBtn').disabled=!history.future.length;status(`${state.territories.filter(f=>!f.properties.parentId).length} 个国家 / 地区 · ${state.cities.length} 座城市 · 本地工作区`);}
function transaction(label,fn){const before=C.clone(state);try{fn();C.validateProject(state);history.push(before);changedState();toast(label+' · 已更新');}catch(e){state=before;sync();toast(e.message);}}
function changedState(){map.invalidateGeometry();revision++;dirty=true;sync();scheduleSave();}
function scheduleSave(){clearTimeout(saveTimer);$('#saveStatus').textContent='● 等待保存';saveTimer=setTimeout(save,700);}
function save(){clearTimeout(saveTimer);const data=JSON.stringify(state),rev=revision;$('#saveStatus').textContent='● 保存中';saveQueue=saveQueue.catch(()=>{}).then(async()=>{try{await persistence.save(JSON.parse(data));if(rev===revision){dirty=false;$('#saveStatus').textContent='● 已保存至'+persistence.label;}}catch(e){$('#saveStatus').textContent='● 保存失败';toast('本地存档失败，请导出项目备份：'+e.message);}});return saveQueue;}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
function select(id,focus=false){selection=id;map.selected=id;renderList();renderDetails();map.draw();const entity=selectedFeature()||selectedCity();if(focus&&entity)map.focus(entity);if(innerWidth<900)document.body.classList.add('mobile-details');}
function renderList(){const query=$('#search').value.trim().toLowerCase();$('#countryCount').textContent=state.territories.length;$('#cityCount').textContent=state.cities.length;$('#countriesTab').classList.toggle('active',tab==='countries');$('#citiesTab').classList.toggle('active',tab==='cities');$('#listLabel').textContent=tab==='countries'?'领土目录':'城市点位';
 const entries=(tab==='countries'?state.territories.map(f=>({...f.properties,_f:f})):state.cities).filter(x=>[x.name,x.alias,x.englishName,x.localName,x.localRomanization,x.fullName,x.realName,...(x.searchAliases||[]),x.id].join(' ').toLowerCase().includes(query)).sort((a,b)=>{if(tab==='countries'){const priority=['song','arcadia','russia','polar','australia','brazil','laplata'];const i=priority.indexOf(a.id),j=priority.indexOf(b.id);if(i>=0||j>=0)return (i<0?999:i)-(j<0?999:j);}return a.name.localeCompare(b.name,'zh');});
 $('#entityList').innerHTML=entries.length?entries.map(x=>{const low=tab==='cities'&&map.elevation(x).z!==null&&map.elevation(x).z<state.seaLevel;return `<button class="entity-row ${selection===x.id?'active':''}" data-id="${esc(x.id)}"><span class="swatch" style="background:${/^#[0-9a-f]{6}$/i.test(x.color)?x.color:low?'#d65e46':'#7f9276'};"></span><span><span class="entity-name">${x.parentId?'↳ ':''}${map.showFeatured&&x.featured?'✦ ':''}${esc(x.name)}</span><small>${esc(tab==='cities'?(low?'低于海平面 · ':'')+(x.englishName||'未填写外文名'):x.alias||x.id)}</small></span>${selection===x.id?'<span class="row-arrow">↗</span>':'<span class="review-dot"></span>'}</button>`;}).join(''):'<div class="empty">没有匹配的档案。<br>可用右上角 ＋ 新建。</div>';
 $$('#entityList button').forEach(b=>b.onclick=()=>select(b.dataset.id,true));
}
function renderDetails(){const f=selectedFeature(),city=selectedCity();if(!f&&!city){$('#details').innerHTML='<p class="muted">点击国家、地区或城市查看档案。</p>';return;}
 if(city){const e=map.elevation(city),low=e.z!==null&&e.z<state.seaLevel,owner=state.territories.find(f=>f.properties.id===city.countryId)?.properties.name||'未指定';$('#selectionType').textContent='CITY / POINT';$('#details').innerHTML=`<div class="country-title"><span class="flag" style="background:${low?'#d65e46':'#8eaa7b'};width:12px;height:12px;margin:10px 0;border-radius:50%"></span><div><h2>${esc(city.name)}</h2><div class="alias">${esc(city.englishName||'未填写外文名')}</div></div></div><p class="country-full">${esc(owner)} · ${esc(C.cityClass(city).label)}（${esc(C.cityClass(city).range)}）${city.capital?(city.capitalRole==='regional'?' · 地区首府':' · 首都 / 中心城市'):''}</p><span class="tag ${low?'pending':''}">${low?'高程低于当前海平面':'城市点位档案'}</span><div class="detail-stats"><div><small>点位地表高程</small><b>${e.z===null?'—':num(e.z)}<span>m</span></b></div><div><small>距情景海平面</small><b>${e.z===null?'—':num(e.z-state.seaLevel)}<span>m</span></b></div></div><div class="notes-grid"><div><small>经度 / LONGITUDE</small>${city.coordinates[0].toFixed(5)}°</div><div><small>纬度 / LATITUDE</small>${city.coordinates[1].toFixed(5)}°</div></div><p class="data-note">高程来源：${esc(e.source)}。点位判别不等同于全城淹没；未计算堤坝、排水与潮汐。</p><p class="detail-description">${esc(city.notes||'暂无城市简介。')}</p><div class="detail-actions"><button id="editEntity">编辑档案</button><button id="moveCity">拖动位置</button></div><div class="detail-actions" style="margin-top:8px"><button id="lookupElevation">查询 90 m DEM</button><button id="deleteEntity" class="danger">删除</button></div>${city.migrationCandidate?'<button id="migrateCity" style="margin-top:12px;width:100%;font-size:10px">迁移到新北市候选点 ↗</button>':''}`;
  if(city.fullName){const title=document.createElement('p');title.className='city-full-name';title.textContent=city.fullName;$('#details .country-title').after(title);}if(city.polityType==='free-city'){const host=state.territories.find(f=>f.properties.id===city.hostCountryId)?.properties.name||'未指定';$('#details .country-full').textContent=`自由市 · 管辖：${owner}${city.capital?' · 首都':''} / 地理所在：${host}`;}decorateDetails(city,true);$('#editEntity').onclick=()=>{enableEditing(true);cityForm(city);};$('#moveCity').onclick=()=>{setTool('moveCity');document.body.classList.remove('mobile-details');};$('#lookupElevation').onclick=()=>lookupElevation(city);$('#deleteEntity').onclick=()=>deleteEntity(city);if($('#migrateCity'))$('#migrateCity').onclick=()=>transaction('迁移城市至新北市候选点',()=>{city.coordinates=[...city.migrationCandidate.coordinates];city.elevation=null;city.elevationSource='迁移后待查询';city.notes+=' 已采用新北市板桥候选点。';});return;
 }
 $('#selectionType').textContent=f.properties.parentId?'REGION / CHILD':'TERRITORY';const p=f.properties,children=state.territories.filter(c=>c.properties.parentId===p.id),cities=state.cities.filter(c=>c.countryId===p.id),area=turf.area(f)/1e6;
 $('#details').innerHTML=`<div class="country-title"><span class="flag" style="background:${/^#[0-9a-f]{6}$/i.test(p.color)?p.color:'#b5c99b'}"></span><div><h2>${esc(p.name)}</h2><div class="alias">${esc(p.alias||'Territory archive')}</div></div></div><p class="country-full">${esc(p.fullName||p.name)}</p><p class="capital-line">首都 / 首府：${esc(p.capital||"待设定")}${p.capitalStatus==="可编辑预设"?" · 可编辑预设":""}</p><span class="tag ${p.needsReview?'pending':''}">${p.needsReview?'栅格提取 · 待核定':'自定义领土'}</span><div class="detail-stats"><div><small>领土面积 · 几何估算</small><b>${num(area/10000)}<span>万 km²</span></b></div><div><small>已记录城市</small><b>${cities.length.toString().padStart(2,'0')}<span>CITIES</span></b></div></div><div class="detail-actions"><button id="editEntity">编辑档案</button><button id="editBorder">调整边界 ↗</button></div><p class="detail-description">${esc(p.notes||'暂无地区简介。')}</p><div class="detail-subhead"><span>下级地区 / ${children.length.toString().padStart(2,'0')}</span><button id="addChild" title="新建下级地区">＋</button></div>${children.slice(0,30).map(c=>`<button class="child-row" data-child="${esc(c.properties.id)}"><span>${esc(c.properties.name)}</span><small>REGION ↗</small></button>`).join('')||'<p class="data-note">在“划归”工具中选省，或新建下级地区。</p>'}<div class="detail-subhead"><span>城市档案 / ${cities.length.toString().padStart(2,'0')}</span><button id="addCountryCity" title="添加城市">＋</button></div>${cities.slice(0,16).map(c=>`<button class="child-row" data-child="${esc(c.id)}"><span>${c.capital?'◎ ':''}${esc(c.name)}</span><small>${c.capital?'CAPITAL':'CITY'} ↗</small></button>`).join('')||'<p class="data-note">尚未记录城市。</p>'}<div class="detail-actions" style="margin-top:18px"><button id="zoomEntity">定位全境</button><button id="deleteEntity" class="danger">删除地区</button></div><p class="data-note">${esc(p.source||'用户创建')}</p>`;
 if(p.localName){const native=document.createElement('div');native.className='country-native';native.innerHTML=`<b lang="${esc(p.localLanguage||'und')}" class="${p.constructedLanguage?'syllabics':'native-serif'}">${esc(p.localName)}</b><span>${esc(p.localRomanization||'')}</span><small>${esc(p.localLanguage||'')} ${p.constructedLanguage?'· 构造语言':''}</small>`;$('#details .country-title').after(native);}if(p.realName){const prototype=document.createElement('p');prototype.className='data-note';prototype.textContent='现实原型：'+p.realName;$('#details .country-full').after(prototype);}if(p.englishName&&p.englishName!==p.alias){const en=document.createElement('p');en.className='country-full country-english';en.textContent=p.englishName;$('#details .country-full').after(en);}decorateDetails(p,false);$('#editEntity').onclick=()=>{enableEditing(true);countryForm(f);};$('#editBorder').onclick=()=>{setTool('vertices');document.body.classList.remove('mobile-details');};$('#addChild').onclick=()=>countryForm(null,p.id);$('#addCountryCity').onclick=()=>searchPlace(p.id);$('#zoomEntity').onclick=()=>map.focus(f);$('#deleteEntity').onclick=()=>deleteEntity(f);$$('[data-child]').forEach(b=>b.onclick=()=>select(b.dataset.child,true));
}
function openModal(title,body,onSubmit,footer=true){$('#modalForm button[type=submit]').textContent=title==='导出地图图片'?'导出图片':'保存';$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalFooter').hidden=!footer;modalSubmit=onSubmit;$('#modal').showModal();}
function closeModal(){$('#modal').close();modalSubmit=null;}
$('#closeModal').onclick=$('#cancelModal').onclick=closeModal;$('#modalForm').onsubmit=e=>{e.preventDefault();if(modalSubmit)modalSubmit(new FormData($('#modalForm')));};
function countryForm(feature=null,parentId=''){enableEditing(true);const p=feature?.properties||{id:'territory-'+crypto.randomUUID(),name:'',alias:'',color:'#a7bd91',parentId};openModal(feature?'编辑地区档案':'新建国家 / 地区',`<div class="form-grid"><label class="full">名称<input name="name" required maxlength="100" value="${esc(p.name)}" placeholder="为这片土地命名"></label><label class="full">全称<input name="fullName" maxlength="250" value="${esc(p.fullName)}"></label><label class="full">英语名称<input name="englishName" maxlength="180" value="${esc(p.englishName||p.alias||'')}"></label><label>简称<input name="abbreviation" maxlength="20" value="${esc(p.abbreviation||'')}"></label><label>其他别名 / 转写<input name="alias" maxlength="150" value="${esc(p.alias)}"></label><label class="full">本地语言名称<input name="localName" value="${esc(p.localName||'')}"></label><label>本地语言转写<input name="localRomanization" value="${esc(p.localRomanization||'')}"></label><label>语言名称 / 代码<input name="localLanguage" value="${esc(p.localLanguage||'')}"></label><label>地图颜色<input name="color" type="color" value="${esc(p.color)}"></label><label class="full">所属上级（留空表示国家）<select name="parentId">${countryOptions(p.parentId)}</select></label><label>人口（未知可留空）<input name="population" type="number" min="0" value="${p.population??''}"></label><label>首都名称<input name="capital" value="${esc(p.capital)}"></label><label class="full">现实对应 / 原型<input name="realName" value="${esc(p.realName||'')}"></label><label class="full check-label"><input type="checkbox" name="featured" ${p.featured?'checked':''}>✦ 明星国家 / 重要地区</label><label class="full">简介 / 设定<textarea name="notes" maxlength="10000">${esc(p.notes)}</textarea></label><label class="full check-label"><input name="reviewed" type="checkbox" ${p.needsReview?'':'checked'}>已核定档案与边界</label></div><p class="data-note">新地区建立后，使用绘制工具确定范围，或划归现成行政区划。</p>`,data=>{transaction(feature?'更新地区档案':'建立地区档案',()=>{const newP={...p,name:data.get('name').trim(),fullName:data.get('fullName'),realName:data.get('realName'),featured:data.has('featured'),alias:data.get('alias'),abbreviation:data.get('abbreviation'),englishName:data.get('englishName'),localName:data.get('localName'),localRomanization:data.get('localRomanization'),localLanguage:data.get('localLanguage'),color:data.get('color'),customColor:!feature||p.customColor||data.get('color')!==p.color,parentId:data.get('parentId')||null,population:data.get('population')===''?null:Number(data.get('population')),capital:data.get('capital'),notes:data.get('notes'),needsReview:!data.has('reviewed')};if(!newP.name)throw Error('名称不能为空');if(newP.parentId===newP.id)throw Error('地区不能作为自己的上级');if(feature)feature.properties=newP;else state.territories.push({type:'Feature',id:p.id,properties:{...newP,source:'用户创建',label:map.proj.invert(map.transform.invert([map.w/2,map.h/2]))},geometry:{type:'MultiPolygon',coordinates:[]}});selection=p.id;});closeModal();if(!feature)setTool('draw');});}
function cityForm(city=null,ll=null,owner=null){enableEditing(true);const c=city||{id:'city-'+crypto.randomUUID(),name:'',coordinates:ll||[0,0],countryId:owner||selectedFeature()?.properties.id||null,origin:'架空新城市'};openModal(city?'编辑城市档案':'新增城市点位',`<div class="form-grid"><label>城市名称<input name="name" required maxlength="100" value="${esc(c.name)}"></label><label>现实对应 / 原名<input name="realName" maxlength="150" value="${esc(c.realName)}"></label><label>经度 °E<input name="lon" type="number" min="-180" max="180" step="any" required value="${c.coordinates[0].toFixed(6)}"></label><label>纬度 °N<input name="lat" type="number" min="-90" max="90" step="any" required value="${c.coordinates[1].toFixed(6)}"></label><label class="full">所属国家 / 地区<select name="countryId">${countryOptions(c.countryId)}</select></label><label>人口<input name="population" type="number" min="0" value="${c.population??''}"></label>${totalsSwitch(c)}<label>点位高程 m（留空使用 DEM）<input name="elevation" type="number" step="any" value="${c.elevation??''}"></label><label class="full check-label"><input name="capital" type="checkbox" ${c.capital?'checked':''}>首都 / 中心城市</label><label class="full">简介 / 定位说明<textarea name="notes" maxlength="10000">${esc(c.notes)}</textarea></label></div><button type="button" id="searchFromCity" style="margin-top:15px">搜索现实地点并定位 ↗</button>`,data=>{transaction(city?'更新城市档案':'添加城市',()=>{const coordinates=[Number(data.get('lon')),Number(data.get('lat'))],elevation=data.get('elevation')===''?null:Number(data.get('elevation')),moved=coordinates.some((v,i)=>v!==c.coordinates[i]);const next={...c,name:data.get('name').trim(),fullName:data.get('fullName'),englishName:data.get('englishName'),localName:data.get('localName'),localLanguage:data.get('localLanguage'),realName:data.get('realName'),coordinates,countryId:data.get('countryId')||null,rank:data.get('rank')||'city',sizeClass:data.get('sizeClass')||'auto',featured:data.has('featured'),includeInNationalTotals:data.has('includeInNationalTotals'),polityType:data.get('polityType')||'ordinary',hostCountryId:data.get('hostCountryId')||null,population:data.get('population')===''?null:Number(data.get('population')),capital:data.has('capital'),notes:data.get('notes'),elevation,elevationSource:elevation===c.elevation&&!moved?c.elevationSource:'用户填写 / 待核定'};if(!next.name)throw Error('城市名称不能为空');if(city)Object.assign(city,next);else state.cities.push(next);selection=c.id;});closeModal();});appendNameForm(c);$('#searchFromCity').onclick=()=>{closeModal();searchPlace(c.countryId,city);};}
function deleteEntity(entity){const city=!!entity.coordinates;const name=city?entity.name:entity.properties.name;openModal('删除 '+name,`<p class="help-copy">${city?'删除该城市点位。':'删除该地区的几何与档案；它的下级地区将转为独立地区，所属城市保留并解除归属。'}此操作可以撤销。</p>`,()=>{transaction('删除 '+name,()=>{if(city)state.cities=state.cities.filter(c=>c.id!==entity.id);else {const id=entity.properties.id;state.territories=state.territories.filter(f=>f.properties.id!==id);for(const f of state.territories)if(f.properties.parentId===id)f.properties.parentId=null;for(const c of state.cities){if(c.countryId===id)c.countryId=null;if(c.hostCountryId===id)c.hostCountryId=null;}}selection=state.territories[0]?.properties.id;});closeModal();});}
function editVertexCoordinates(point){openModal('边界顶点坐标',`<p class="help-copy">可拖动顶点，也可输入经纬度。具有相同坐标的共享顶点会同步移动。</p><div class="form-grid"><label>经度<input name="lon" type="number" step="any" min="-180" max="180" required value="${point[0]}"></label><label>纬度<input name="lat" type="number" step="any" min="-90" max="90" required value="${point[1]}"></label></div>`,data=>{transaction('移动共享顶点',()=>{C.moveShared(state.territories,point,[Number(data.get('lon')),Number(data.get('lat'))]);if(turf.kinks(selectedFeature()).features.length)throw Error('移动会造成边界自交');});closeModal();});}
async function ensureAdmin(){if(baseAdmin)return;status('正在读取全球省级区划…');try{baseAdmin=(await (await fetch('data/admin1.geojson')).json()).features;map.setAdmin([...baseAdmin,...(state.adminExtras||[])]);status(`省级底稿已就绪 · ${baseAdmin.length} 个区划`);}catch(e){toast('区划底稿载入失败：'+e.message);}}
function setTool(tool){if(tool!=='select'&&map.kind==='globe'){map.setProjection('robinson');updateGlobeUI();toast('已切换平面视图，便于精确编辑');}if(tool!=='select')enableEditing(true);if(['draw','vertices'].includes(tool)&&!selectedFeature()){toast('请先选择或新建一个国家 / 地区');return;}map.tool=tool;map.drawPoints=[];map.adminSelection=null;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#drawActions').hidden=tool!=='draw';const help={vertices:'拖动方形顶点调整边界；单击输入精确坐标。双击边线插点，右键删点。滚轮可继续放大。',draw:'点击地图逐点绘制，按 Enter 完成、Backspace 退一步。新范围归入所选地区，自动裁去其他国家的重叠部分。',assign:'点击省级底稿，选择所属国家。可把省作为下级地区保存。',city:'点击空白处添加城市；拖动已有城市可改位置。也可使用现实地点搜索。',moveCity:'拖动城市标记，或点击地图移动当前城市。位置改变后会清除旧高程，重新取样。'};$('#toolHelp').textContent=help[tool]||'';$('#toolHelp').hidden=!help[tool];if(tool==='assign'){map.layers.admin=true;$('#layerAdmin').checked=true;ensureAdmin();}map.draw();}
function polygonOperation(patch,targetId,makeChild=null){C.validateFeature(patch);if(turf.kinks(patch).features.length)throw Error('多边形自交，请重新绘制');const target=state.territories.find(f=>f.properties.id===targetId);if(!target)throw Error('请指定目标国家');
 if(target.properties.parentId){const parent=state.territories.find(f=>f.properties.id===target.properties.parentId);patch=turf.intersect(turf.featureCollection([patch,parent]));if(!patch)throw Error('下级地区必须位于上级境内');target.geometry=target.geometry.coordinates.length?turf.union(turf.featureCollection([target,patch])).geometry:patch.geometry;return;}
 const box=turf.bbox(patch);const overlaps=f=>{const b=turf.bbox(f);return b[0]<=box[2]&&b[2]>=box[0]&&b[1]<=box[3]&&b[3]>=box[1];};
 for(const f of state.territories){if(f.properties.id===targetId||f.properties.parentId||!f.geometry.coordinates.length||!overlaps(f))continue;const result=turf.difference(turf.featureCollection([f,patch]));f.geometry=result?.geometry||{type:'MultiPolygon',coordinates:[]};}
 target.geometry=target.geometry.coordinates.length?turf.union(turf.featureCollection([target,patch])).geometry:patch.geometry;
 for(const f of state.territories.filter(f=>f.properties.parentId)){const parent=state.territories.find(p=>p.properties.id===f.properties.parentId);if(parent&&overlaps(f)){const clipped=parent.geometry.coordinates.length?turf.intersect(turf.featureCollection([f,parent])):null;f.geometry=clipped?.geometry||{type:'MultiPolygon',coordinates:[]};}}
 if(makeChild){const exists=state.territories.find(f=>f.properties.id===makeChild.id);if(exists){exists.geometry=patch.geometry;exists.properties.parentId=targetId;}else state.territories.push({type:'Feature',id:makeChild.id,geometry:patch.geometry,properties:{id:makeChild.id,name:makeChild.name,alias:makeChild.originalName||'',color:target.properties.color,parentId:targetId,label:turf.pointOnFeature(patch).geometry.coordinates,source:makeChild.source||'导入区划',needsReview:false,notes:'由行政区划底稿划归，可继续编辑。'}});}
 target.properties.needsReview=false;
}
function finishDraw(){if(map.drawPoints.length<3){toast('至少需要 3 个不同顶点');return;}const ll=map.drawPoints.map(p=>p.map(v=>+v.toFixed(6)));if(ll.some((p,i)=>i&&Math.abs(p[0]-ll[i-1][0])>180)){toast('跨日界线范围请分两次绘制，避免连接到世界另一侧');return;}ll.push([...ll[0]]);transaction('更新领土范围',()=>polygonOperation(turf.polygon([ll]),selection));map.drawPoints=[];setTool('vertices');}
function assignRegion(f){const current=selectedFeature();openModal('划归 '+f.properties.name,`<p class="help-copy">将这个现实区划用作架空领土底稿；同一区域会从其他国家中扣除。源资料：${esc(f.properties.source)}。</p><div class="form-grid"><label class="full">目标国家<select name="target">${countryOptions(current?.properties.parentId||current?.properties.id,false)}</select></label><label class="full check-label"><input name="child" type="checkbox" checked>同时建立可编辑的下级地区</label></div>`,data=>{transaction('完成区划归属调整',()=>{polygonOperation(f,data.get('target'),data.has('child')?{...f.properties,id:'region-'+f.properties.id}:null);selection=data.get('target');});map.adminSelection=null;closeModal();});}
function updateSeaUI(){$('#coastNote').textContent=map.view==='nightlights'?'现实 2016 灯光参考，不随情景海平面或架空人口重新计算。':map.illustratedCoast()?'依实际连海淹没区域拟合 · '+state.seaLevel+' m；0.1° 高程概览，非沿海精测。':'当前使用 DEM 连通淹没示意；全球高程网格为 0.1°。';$('#seaNumber').value=state.seaLevel;$('#seaSlider').value=Math.max(-20,Math.min(100,state.seaLevel));$('#seaBadge').innerHTML=`${esc(state.seaYear||'SEA LEVEL')} <b>${state.seaLevel>0?'+':''}${Number(state.seaLevel.toFixed(2))} m</b>`;$$('[data-sea]').forEach(b=>b.classList.toggle('active',Number(b.dataset.sea)===state.seaLevel&&(!b.dataset.year||Number(b.dataset.year)===state.seaYear)));$('#surfaceMode').value=state.mode;}
function changeSea(value,year=null){if(!Number.isFinite(value)||value<-500||value>1000){toast('海平面范围：−500 至 +1000 m');updateSeaUI();return;}transaction('海平面 '+value+' m',()=>{state.seaLevel=value;state.seaYear=year;state.seaScenario={baselineYear:1986,baselineLevel:0,referenceYear:2025,referenceLevel:3.7,method:'linear',annualRate:3.7/39};});map.requestTerrain();}
function showCoordinates(ll){if(!ll){$('#coordinates').textContent='WGS 84 / —';return;}const z=C.sampleDem(map.customDem,...ll)??C.sampleDem(map.dem?{...map.dem,values:map.dem[state.mode]}:null,...ll);$('#coordinates').textContent=`${Math.abs(ll[0]).toFixed(3)}° ${ll[0]<0?'W':'E'}  ${Math.abs(ll[1]).toFixed(3)}° ${ll[1]<0?'S':'N'}  /  ${z===null?'—':Math.round(z)+' m'}`;}
function showHover(entity,position){const el=$('#mapTooltip');if(!entity){el.hidden=true;return;}const city=!!entity.coordinates;let detail=city?[entity.englishName,entity.localName].filter(Boolean).join(' / ')||entity.realName||'架空城市':entity.properties.alias||entity.properties.originalName||'领土档案';if(city){const e=map.elevation(entity);detail+=' · '+(e.z===null?'高程未知':num(e.z)+' m'+(e.z<state.seaLevel?' 低于情景海平面':''));}el.innerHTML=esc(city?entity.name:entity.properties.name)+`<small>${esc(detail)}</small>`;el.style.left=Math.min(position.x+15,map.w-220)+'px';el.style.top=Math.max(115,position.y-47)+'px';el.hidden=false;}
async function searchPlace(owner=null,existing=null){openModal('搜索现实地点',`<p class="help-copy">搜索本地 7,342 个世界城市点位，也可联网查找更多地点。选定后可改名并拖动位置。</p><div class="search" style="margin:0 0 12px"><input id="placeQuery" aria-label="现实地点名称" placeholder="例如 上海 / Murray Bridge / Itanagar"><button id="onlineSearch" type="button" style="white-space:nowrap;font-size:10px">联网搜索 ↗</button></div><div id="placeResults" style="max-height:350px;overflow:auto"></div><p class="data-note">本地：Natural Earth。联网：Open-Meteo / GeoNames；联网时只发送你输入的地名。</p>`,null,false);
 const show=places=>{$('#placeResults').innerHTML=places.length?places.map((p,i)=>`<button class="child-row" data-place="${i}"><span>${esc(p.name)}<small>${esc(p.realName||'')} · ${esc(p.country||'')}</small></span><small>${p.coordinates.map(v=>v.toFixed(3)).join(', ')} ↗</small></button>`).join(''):'<p class="muted">未找到匹配地点。可尝试英文名或联网搜索。</p>';$$('[data-place]').forEach(b=>b.onclick=()=>{const p=places[Number(b.dataset.place)];closeModal();const c=existing?{...existing,coordinates:p.coordinates,elevation:null}:null;cityForm(c,p.coordinates,owner);if(!existing){$('#modalForm [name=name]').value=p.name;$('#modalForm [name=realName]').value=p.realName||p.name;$('#modalForm [name=englishName]').value=p.realName||p.name;$('#modalForm [name=localName]').value=p.name;const country=countryAt(p.coordinates);if(country&&!owner)$('#modalForm [name=countryId]').value=country.properties.id;}map.focus({coordinates:p.coordinates});if(existing){modalSubmit=data=>{transaction('更新城市定位',()=>{Object.assign(existing,c,{name:data.get('name'),fullName:data.get('fullName'),englishName:data.get('englishName'),localName:data.get('localName'),localLanguage:data.get('localLanguage'),realName:data.get('realName'),coordinates:[Number(data.get('lon')),Number(data.get('lat'))],countryId:data.get('countryId')||null,rank:data.get('rank')||'city',sizeClass:data.get('sizeClass')||'auto',featured:data.has('featured'),includeInNationalTotals:data.has('includeInNationalTotals'),polityType:data.get('polityType')||'ordinary',hostCountryId:data.get('hostCountryId')||null,elevation:data.get('elevation')===''?null:Number(data.get('elevation')),elevationSource:'移动后 / 用户填写',notes:data.get('notes'),capital:data.has('capital'),population:data.get('population')===''?null:Number(data.get('population'))});});closeModal();};}});};
 const searchLocal=()=>{const q=$('#placeQuery').value.trim().toLowerCase();show(q?gazetteer.filter(p=>[p.name,p.realName,p.country].join(' ').toLowerCase().includes(q)).slice(0,30):[]);};$('#placeQuery').oninput=searchLocal;
 $('#onlineSearch').onclick=async()=>{const q=$('#placeQuery').value.trim();if(q.length<2){toast('请输入至少两个字');return;}const button=$('#onlineSearch');button.disabled=true;button.textContent='查询中…';try{const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(q)+'&count=10&language=zh&format=json',{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('服务响应 '+r.status);const data=await r.json();if($('#placeResults'))show((data.results||[]).map(x=>({name:x.name,realName:x.name,country:[x.country,x.admin1].filter(Boolean).join(' / '),coordinates:[x.longitude,x.latitude]})));}catch(e){toast('联网检索失败，本地城市搜索仍可用。'+e.message);}finally{if(button.isConnected){button.disabled=false;button.textContent='联网搜索 ↗';}}};$('#placeQuery').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#onlineSearch').click();}};$('#placeQuery').focus();}
function countryAt(ll){return state.territories.find(f=>!f.properties.parentId&&f.geometry.coordinates.length&&turf.booleanPointInPolygon(ll,f));}
async function lookupElevation(city){const coords=[...city.coordinates];$('#lookupElevation').disabled=true;try{const r=await fetch(`https://api.open-meteo.com/v1/elevation?latitude=${coords[1]}&longitude=${coords[0]}`,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('服务响应 '+r.status);const z=(await r.json()).elevation?.[0];if(!Number.isFinite(z))throw Error('无有效高程数据');if(city.coordinates.some((v,i)=>v!==coords[i])){toast('城市已移动，忽略旧点位查询结果');return;}transaction('更新城市高程',()=>{city.elevation=z;city.elevationSource='Open-Meteo / Copernicus GLO-90 · 90 m · EGM2008';});}catch(e){toast('高程查询失败：'+e.message);}finally{if($('#lookupElevation'))$('#lookupElevation').disabled=false;}}
function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data)],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importDialog(){openModal('导入数据',`<div class="import-options"><button type="button" id="importProject">ATLAS 项目 / GeoJSON / TopoJSON<small>恢复存档，或添加国家、地区与细分行政区划。</small></button><button type="button" id="importDem">高程 GeoTIFF<small>WGS84 经纬度、米制高程；可替换局部地区的全球概览。</small></button><button type="button" id="importBoundary">在线获取更细区划<small>geoBoundaries ADM1 / ADM2，按现实国家代码查询。</small></button></div>`,null,false);$('#importProject').onclick=()=>$('#fileInput').click();$('#importDem').onclick=()=>$('#demInput').click();$('#importBoundary').onclick=boundaryDialog;}
async function handleFile(file){if(!file)return;if(file.size>100*1024*1024){toast('文件超过 100 MB，请先按地区拆分');return;}try{const data=JSON.parse(await file.text());if(data.version===1){C.validateProject(data);transaction('导入项目存档',()=>{state=data;selection=state.territories[0]?.properties.id;});map.setCustomDem(state.customDem);map.requestTerrain();if(baseAdmin)map.setAdmin([...baseAdmin,...(state.adminExtras||[])]);closeModal();return;}
  let features;if(data.type==='Topology')features=Object.values(data.objects).flatMap(o=>{const f=topojson.feature(data,o);return f.type==='FeatureCollection'?f.features:[f];});else features=data.type==='FeatureCollection'?data.features:data.type==='Feature'?[data]:null;
  if(!features?.length)throw Error('没有可导入的 GeoJSON 要素');if(features.length>15000)throw Error('单次最多 15,000 个区划，请拆分文件');for(const f of features){f.properties=f.properties||{};C.validateFeature(f);}closeModal();previewFeatures(features,file.name);
 }catch(e){toast('导入失败：'+e.message);}finally{$('#fileInput').value='';}}
function previewFeatures(features,source){openModal('导入 '+features.length+' 个区划',`<p class="help-copy">文件：${esc(source)}。仅接受 WGS84 经纬度坐标。可以用作划归底稿，也可以创建自己的国家 / 地区。</p><div class="form-grid"><label class="full">用途<select name="mode"><option value="admin">行政区划底稿（用于划归）</option><option value="territories">架空国家 / 地区</option></select></label><label class="full">名称字段<input name="nameField" value="${esc(['name','NAME_ZH','shapeName','NAME','name_zh'].find(k=>features[0].properties[k])||'name')}"></label></div>`,data=>{transaction('导入区划数据',()=>{const list=features.map((f,i)=>{const id='import-'+crypto.randomUUID();return {type:'Feature',id,geometry:f.geometry,properties:{id,name:String(f.properties[data.get('nameField')]||'导入地区 '+(i+1)),originalName:f.properties.name||'',alias:f.properties.alias||'',color:/^#[0-9a-f]{6}$/i.test(f.properties.color)?f.properties.color:'#abc499',parentId:null,label:turf.pointOnFeature(f).geometry.coordinates,source,needsReview:false}};});if(data.get('mode')==='admin')state.adminExtras=[...(state.adminExtras||[]),...list];else {state.territories.push(...list);selection=list[0].id;}});closeModal();if(data.get('mode')==='admin'){ensureAdmin().then(()=>map.setAdmin([...baseAdmin,...state.adminExtras]));map.layers.admin=true;$('#layerAdmin').checked=true;}});}
function boundaryDialog(){closeModal();openModal('获取更细行政区划',`<p class="help-copy">geoBoundaries gbOpen 提供各国开放区划。ADM2 在不同国家对应不同层级，未必是“市”。查询只下载底稿，不改变架空国界。</p><div class="form-grid"><label>三位国家代码<input name="iso" value="CHN" pattern="[A-Za-z]{3}" required maxlength="3"></label><label>层级<select name="level"><option>ADM2</option><option>ADM1</option></select></label></div><p id="boundaryStatus" class="data-note">来源：geoBoundaries / William & Mary。授权信息将随底稿保存。</p>`,async data=>{const button=$('#modalFooter button[type=submit]');button.disabled=true;try{const iso=data.get('iso').toUpperCase(),level=data.get('level');$('#boundaryStatus').textContent='查询数据集与授权信息…';const r=await fetch(`https://www.geoboundaries.org/api/current/gbOpen/${iso}/${level}/`,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('暂无该层级数据，或服务暂不可用');const meta=await r.json();const url=meta.simplifiedGeometryGeoJSON||meta.gjDownloadURL;if(!url||!/^https:\/\//.test(url))throw Error('没有可用下载链接');$('#boundaryStatus').textContent='下载边界几何…';const response=await fetch(url,{signal:AbortSignal.timeout(90000)});if(!response.ok)throw Error('下载失败');const geo=await response.json();for(const f of geo.features)C.validateFeature(f);closeModal();previewFeatures(geo.features,`geoBoundaries ${iso} ${level} · ${meta.boundaryLicense||'gbOpen'} · ${meta.boundarySource||''} · ${url}`);}catch(e){$('#boundaryStatus').textContent='获取失败：'+e.message+'。可从 geoBoundaries 官网下载后导入 GeoJSON。';}finally{button.disabled=false;}});}
async function importDem(file){if(!file)return;try{if(file.size>250*1024*1024)throw Error('GeoTIFF 超过 250 MB，请先裁剪');const tif=await GeoTIFF.fromArrayBuffer(await file.arrayBuffer()),image=await tif.getImage(),keys=image.getGeoKeys(),dir=image.getFileDirectory();if(keys.GeographicTypeGeoKey!==4326||keys.ProjectedCSTypeGeoKey)throw Error('请先在 GIS 软件中重投影到 EPSG:4326');if(dir.ModelTransformation)throw Error('暂不支持旋转网格，请先转换为北向上规则网格');const bbox=image.getBoundingBox(),factor=Math.max(1,image.getWidth()/2048,image.getHeight()/2048),width=Math.floor(image.getWidth()/factor),height=Math.floor(image.getHeight()/factor);if(width<2||height<2)throw Error('DEM 尺寸不足');const rasters=await image.readRasters({samples:[0],width,height,resampleMethod:'nearest'}),nd=image.getGDALNoData(),values=Array.from(rasters[0],v=>!Number.isFinite(v)||v===nd?null:v);closeModal();openModal('确认高程基准',`<p class="help-copy">${esc(file.name)}<br>${width} × ${height}，范围 ${bbox.map(v=>v.toFixed(3)).join(', ')}。${factor>1?'已降采样到浏览器可处理的概览；原始精度未保留。':''}</p><div class="form-grid"><label class="full">垂直基准说明<input name="datum" required placeholder="例如 EGM2008 / 当地平均海平面"></label><label class="full">加到原始高程的偏移量（m）<input name="offset" type="number" step="any" value="0" required></label></div><p class="data-note">导入数据必须以米为单位。局部淹没采用边缘海洋连通种子，不计算堤防或地下连通。基准不一致会影响 +3.7 m 判断。</p>`,data=>{transaction('导入局部 DEM',()=>{const offset=Number(data.get('offset'));state.customDem={name:file.name,width,height,bbox,values:values.map(v=>v===null?null:v+offset),datum:data.get('datum'),offset,source:'用户 GeoTIFF',resolutionDegrees:(bbox[2]-bbox[0])/width};});map.setCustomDem(state.customDem);$('#demStatus').textContent=`局部 DEM：${file.name} · ${width} × ${height}`;closeModal();});}catch(e){toast('DEM 导入失败：'+e.message);}finally{$('#demInput').value='';}}
function dataDialog(){openModal('数据来源与精度',`<div class="help-copy"><p><b>架空领土</b><br>用户最新有标注原图 5146 × 2631；非洲以此为准，旧空白图仅作参照。基于色块提取并按 Robinson 投影（中央经线约 11°E）配准。保留原图，可逐区核定。图上一个像素代表数公里，文字、细小岛屿、贴边色块及投影配准均可能带来误差。</p><p><b>行政区划与城市</b><br><a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Natural Earth</a> 公共领域，1:10m 比例尺，4,596 个 ADM1 区划与 7,342 个城市检索点。1:10m 指一千万分之一，并非 10 米精度。架空归属由本项目定义。</p><p><b>高程 / 冰面 / 冰下基岩</b><br><a href="https://www.ncei.noaa.gov/products/etopo-global-relief-model" target="_blank" rel="noreferrer">NOAA ETOPO 2022</a>，EGM2008 米制高程。本地全球概览 3600 × 1800（0.1°，赤道约 11 km），取样自 60″ 数据；另有 Natural Earth 冰川范围。北极浮冰不视为陆地，冰川范围不代表季节性海冰。</p><p><b>城市低地标记</b><br>红色城市符号 = 点位高程低于当前海平面。优先使用城市的 90 m DEM 查询或用户高程，然后使用局部 DEM，最后才是 ETOPO 概览。<a href="https://open-meteo.com/en/docs/elevation-api" target="_blank" rel="noreferrer">Open-Meteo / Copernicus GLO-90</a> 为城市提供更细采样，仍不能判定整座城市是否淹没。</p><p><b>淹没区域拟合海岸线</b><br>以实际蓝色连通淹没栅格为基础提取边缘，局部平滑，并仅在新淹没区附近衔接共同大陆轮廓；没有沿全部海岸作等宽退缩。支持 3.7、5.03 m。全球 0.1° 网格只能作示意，不是精确海岸预测。南极沿用现实轮廓；其他水位、局部 DEM 及基岩模式使用原始 DEM 连通层。</p><p><b>夜景底图</b><br>NASA Black Marble 2016 彩色合成，3600×1800 全球概览。展示现实灯光分布，不按架空人口、国界或海平面重新计算。<a href="https://science.nasa.gov/earth/earth-observatory/earth-at-night/maps/" target="_blank" rel="noreferrer">NASA 来源</a></p><p><b>常规地图与地球仪</b><br>浅色道路地图采用 Natural Earth 主要道路和河流，保留架空国界与地名；不提供街道导航。地球仪可拖动旋转、缩放，点击目录可转到相应位置。进入几何编辑时切回平面以便精确操作。</p><p><b>海平面情景</b><br>青色区域 = 从既有海洋扩展、四邻域连通且低于海平面的栅格。现实基准 / 1986 年为 0 m，2025 年为 +3.7 m；按 39 年平均速率 3.7/39 m/年匀速外推，2039 年约 +5.03 m。这是小说情景推算，未假定加速度。阈值模型不包含堤坝、潮汐、排水、地面沉降或冰盖动力学；“基岩”视图也不是现实融冰预测。</p><p><b>更高精度</b><br>导入 EPSG:4326、米制且垂直基准明确的 GeoTIFF。局部 DEM 最长边保留到 2048 像素。下级区划可从 <a href="https://www.geoboundaries.org/api.html" target="_blank" rel="noreferrer">geoBoundaries</a> 获取，授权信息跟随导入数据。</p><p><b>本地存档</b><br>本地程序自动写入 storage/project.json；在线版保存在当前浏览器的 IndexedDB，不会提交到网站或其他设备。清除网站数据会删除浏览器存档，请用 JSON 导出备份。导出项目包含自定义领土、城市、局部 DEM 和新增区划。原始全球 DEM 与城市库随程序目录保存。</p><button type="button" id="downloadTerritories">导出领土 GeoJSON</button><button type="button" id="downloadCities">导出城市 GeoJSON</button><button type="button" id="removeCustomDem">移除局部 DEM</button></div>`,null,false);$('#downloadTerritories').onclick=()=>download('atlas-territories.geojson',{type:'FeatureCollection',features:state.territories});$('#downloadCities').onclick=()=>download('atlas-cities.geojson',{type:'FeatureCollection',features:state.cities.map(c=>({type:'Feature',properties:{...c,coordinates:undefined},geometry:{type:'Point',coordinates:c.coordinates}}))});$('#removeCustomDem').disabled=!state.customDem;$('#removeCustomDem').onclick=()=>{transaction('移除局部 DEM',()=>state.customDem=null);map.setCustomDem(null);$('#demStatus').textContent='NOAA ETOPO · 0.1° 全球概览 · 非沿海精测';closeModal();};}
function helpDialog(){openModal('从这里开始，构建你的世界',`<div class="help-copy"><p><b>探索</b> · 拖动平移、滚轮缩放。点击国家或城市查看档案，目录点击可定位。切换极地投影能完整查看南北极。</p><p><b>划归 A</b> · 打开省级底稿，点击省区，选择架空国家。选中“建立下级地区”可以继续细分。</p><p><b>边界 E</b> · 拖动所选地区的方形顶点，单击输入经纬度；双击边线插入顶点，右键删除。相同坐标的共享顶点同步移动；初始栅格提取边界未建立完整共享拓扑，细部需校核。</p><p><b>绘制 D</b> · 选择国家后逐点画范围；Enter 完成，Backspace 退一步，Esc 取消。新范围从其他国家扣除并归入目标。跨日界线请分两次画。</p><p><b>城市 C</b> · 点击地图新增城市；拖动城市可以改变位置。档案中“搜索现实地点”支持离线检索和联网搜索，然后可改成架空名称。</p><p><b>海平面</b> · 红色菱形标记低于海平面的点位，青色显示海洋连通的新增淹没格网。它们表达不同信息。</p><p><b>存档</b> · 修改自动保存，Ctrl+Z 撤销，Ctrl+Shift+Z 重做。建议阶段性导出项目文件。</p><p><b>等高线</b> · 地形视图使用真实 DEM；等高线默认等高距 500 m，可在下方修改。</p><label>等高距（m）<select id="contourInterval"><option value="50">50（适合局部 DEM）</option><option value="100">100</option><option value="250">250</option><option value="500" selected>500</option><option value="1000">1000</option></select></label><p class="data-note">手机 / 窄屏点击对象会展开详情；点击专注可关闭详情面板。</p></div>`,null,false);$('#contourInterval').value=map.interval||500;$('#contourInterval').onchange=e=>{map.interval=Number(e.target.value);map.requestTerrain();};}
$('#search').oninput=renderList;$('#countriesTab').onclick=()=>{tab='countries';renderList();};$('#citiesTab').onclick=()=>{tab='cities';renderList();};$('#newCountry').onclick=()=>tab==='cities'?searchPlace():countryForm();$$('[data-tool]').forEach(b=>b.onclick=()=>{setTool(b.dataset.tool);if(b.dataset.tool==='city')searchPlace();});
$('#zoomIn').onclick=()=>map.zoomBy(1.6);$('#zoomOut').onclick=()=>map.zoomBy(1/1.6);$('#resetView').onclick=()=>map.reset();$('#focusBtn').onclick=()=>{document.body.classList.toggle('focus');document.body.classList.remove('mobile-details');};$('#projection').onchange=e=>{if(map.view==='reference'){setView('political');}map.setProjection(e.target.value);updateGlobeUI();};
function updateGlobeUI(){$('#globeToggle').textContent=map.kind==='globe'?'▱ 平面地图':'◎ 地球仪';$('#globeToggle').setAttribute('aria-pressed',map.kind==='globe');$('#projection').value=map.kind;}
$('#globeToggle').onclick=()=>{if(map.view==='reference')setView('political');if(map.tool!=='select')setTool('select');map.setProjection(map.kind==='globe'?'robinson':'globe');updateGlobeUI();toast(map.kind==='globe'?'拖动球体旋转，滚轮缩放；点击目录可转到对应地区':'已切换平面地图');};
function setView(view){$('.palette-control').hidden=view!=='political';const names={standard:['常规地图','道路与河流',''],political:['世界政区','', ''],terrain:['分层地形','', ''],contours:['等高线','', ''],nightlights:['夜景图','现实灯光 · 2016',''],reference:['原图对照','海平面 0 m','']};$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#viewTitle').innerHTML=names[view][0]+'<span>'+names[view][1]+'</span>';$('#viewSubtitle').textContent=names[view][2];map.setView(view);updateGlobeUI();updateSeaUI();
 if(view==='reference'){$('#legend').innerHTML='<button id="reference1" style="font-size:9px;padding:5px">图1 · 国家与城市</button><button id="reference2" style="font-size:9px;padding:5px">图2 · 旧版参照</button>';$('#legend').style.pointerEvents='auto';$('#reference1').onclick=()=>{map.referenceIndex=0;map.draw();};$('#reference2').onclick=()=>{map.referenceIndex=1;map.draw();};}
 else if(view==='nightlights')$('#legend').innerHTML='NASA Black Marble · 2016 现实灯光参考';
 else if(view==='standard')$('#legend').innerHTML='浅蓝水域 · 米白陆地 · 主要道路 / 河流（概览）';
 else if(view==='political')$('#legend').innerHTML='<span class="legend-line"></span>架空国界 <span style="background:#d65e46;width:6px;height:6px;border-radius:50%;margin-left:10px"></span>低于海平面 <span style="background:#309eac;width:8px;height:8px;margin-left:8px"></span>新增淹没';
 else $('#legend').innerHTML='<span style="display:inline-block;width:110px;height:6px;background:linear-gradient(90deg,#82aab0,#b6cba5,#ded0a6,#ae9d93,#e8e4db)"></span> −6,000 → 6,000 m';}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
const layerIds={layerTerritories:'territories',layerAdmin:'admin',layerCities:'cities',layerIce:'ice',layerFlood:'flood'};Object.entries(layerIds).forEach(([id,key])=>$('#'+id).onchange=async e=>{map.layers[key]=e.target.checked;if(key==='admin')await ensureAdmin();if(key==='ice'&&!map.ice){map.setIce((await (await fetch('data/ice.geojson')).json()).features);}map.draw();if(key==='flood')map.requestTerrain();});
$$('[data-sea]').forEach(b=>b.onclick=()=>changeSea(b.dataset.year==='2039'?Number(C.seaLevelAt(2039).toFixed(2)):Number(b.dataset.sea),b.dataset.year?Number(b.dataset.year):null));$('#seaNumber').onchange=e=>changeSea(Number(e.target.value));$('#seaSlider').oninput=e=>{$('#seaNumber').value=e.target.value;};$('#seaSlider').onchange=e=>changeSea(Number(e.target.value));$('#coastMode').onchange=e=>{transaction('切换海岸线显示',()=>state.coastMode=e.target.value);map.terrain=null;map.draw();map.requestTerrain();};$('#surfaceMode').onchange=e=>{transaction('切换高程表面',()=>state.mode=e.target.value);map.requestTerrain();};
$('#undoBtn').onclick=()=>{const prev=history.undo(state);if(prev){state=prev;map.setCustomDem(state.customDem);changedState();map.requestTerrain();}};$('#redoBtn').onclick=()=>{const next=history.redo(state);if(next){state=next;map.setCustomDem(state.customDem);changedState();map.requestTerrain();}};
$('#finishDraw').onclick=finishDraw;$('#cancelDraw').onclick=()=>setTool('select');$('#importBtn').onclick=importDialog;$('#exportBtn').onclick=()=>{download('随星录-世界图志-'+new Date().toISOString().slice(0,10)+'.json',state);toast('已导出完整项目');};$('#fileInput').onchange=e=>handleFile(e.target.files[0]);$('#demInput').onchange=e=>importDem(e.target.files[0]);$('#helpBtn').onclick=helpDialog;$('#dataBtn').onclick=dataDialog;
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||$('#modal').open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();(e.shiftKey?$('#redoBtn'):$('#undoBtn')).click();return;}if(e.key==='/'){e.preventDefault();$('#search').focus();}if(e.key==='Escape'){setTool('select');document.body.classList.remove('mobile-details');}if(e.key==='Enter'&&map.tool==='draw')finishDraw();if(e.key==='Backspace'&&map.tool==='draw'){e.preventDefault();map.drawPoints.pop();map.draw();}const tools={v:'select',e:'vertices',d:'draw',a:'assign',c:'city'};if(tools[e.key.toLowerCase()])setTool(tools[e.key.toLowerCase()]);});
async function start(){try{const [territories,cities,saved,gaz]=await Promise.all([fetch('data/territories.geojson').then(r=>r.json()),fetch('data/cities.json').then(r=>r.json()),persistence.load(),fetch('data/gazetteer.json').then(r=>r.ok?r.json():[])]);gazetteer=gaz;if(saved){try{C.validateProject(saved);state=saved;}catch(e){throw Error('现有存档无效，请从 storage/project.previous.json 恢复。'+e.message);}}else {state.territories=territories.features;state.cities=cities;}
  if(!state.territories.some(f=>f.properties.id===selection))selection=state.territories[0]?.properties.id;map.referenceImages=['data/reference-current.png','data/reference-regions.png'].map(url=>{const image=new Image();image.onload=()=>map.draw();image.src=url;return image;});map.resize();sync();setView('political');map.loadWater().catch(e=>toast(e.message));map.loadCoast().then(()=>map.requestTerrain()).catch(e=>toast(e.message));$('#saveStatus').textContent=saved?'● 已读取'+persistence.label+'存档':'● 发布底稿';loadCompleted=true;
  const meta=await fetch('data/elevation.json').then(r=>r.json());const [surface,bed]=await Promise.all(['surface','bed'].map(s=>fetch(`data/elevation-${s}.f32`).then(r=>{if(!r.ok)throw Error('高程文件缺失');return r.arrayBuffer();}).then(a=>new Float32Array(a))));map.setDem({...meta,surface,bed});if(state.customDem)map.setCustomDem(state.customDem);$('#demStatus').textContent=state.customDem?`局部 DEM：${state.customDem.name}`:'NOAA ETOPO · 0.1° 全球概览 · 非沿海精测';renderList();renderDetails();map.draw();
 }catch(e){toast('载入失败：'+e.message);status('载入失败：'+e.message);$('#saveStatus').textContent='● 需要检查';console.error(e);}}

for(const [key,id] of [['zh','countryLangZh'],['en','countryLangEn'],['local','countryLangLocal']])$('#'+id).onchange=e=>transaction('切换国名显示',()=>{state.countryNameLanguages={...(state.countryNameLanguages||{zh:true,en:true,local:true}),[key]:e.target.checked};});
function renderPalette(){const box=$('#paletteSwatches');box.replaceChildren(...state.territories.filter(f=>!f.properties.parentId).slice(0,8).map(f=>{const swatch=document.createElement('i');swatch.style.background=map.fillColor(f);return swatch;}));}
$('#palette').onchange=e=>transaction('切换政区配色',()=>state.palette=e.target.value);
function applyTheme(theme){document.documentElement.dataset.theme=theme;map.night=theme==='dark';$('#themeToggle').textContent=map.night?'☀ 日间':'☾ 夜间';$('#themeToggle').setAttribute('aria-pressed',map.night);}
$('#themeToggle').onclick=()=>{transaction('切换显示主题',()=>state.theme=state.theme==='dark'?'light':'dark');map.terrain=null;map.draw();map.requestTerrain();};
$('#panelToggle').onclick=()=>document.body.classList.toggle('mobile-details');
let editing=false;
function enableEditing(value){editing=value;document.body.classList.toggle('editing',value);$('#editModeBtn').textContent=value?'完成编辑':'编辑模式';$('#editorBanner').hidden=!value;if(!value&&map.tool!=='select')setTool('select');}
$('#editModeBtn').onclick=()=>{enableEditing(!editing);if(!editing&&dirty)save();};
$('#editorSave').onclick=()=>{save();$('#exportBtn').click();};
for(const [key,id] of [['zh','langZh'],['en','langEn'],['local','langLocal']])$('#'+id).onchange=e=>{state.nameLanguages={...(state.nameLanguages||{zh:true,en:true,local:true}),[key]:e.target.checked};changedState();};
function appendNameForm(c){const box=document.createElement('div');box.className='form-grid';box.style.marginTop='18px';box.innerHTML=`<label class="full">城市全称<input name="fullName" maxlength="250" value="${esc(c.fullName||'')}"></label><label class="full">人口等级<select name="sizeClass"><option value="auto">按人口自动分级</option>${C.CITY_CLASSES.map(g=>`<option value="${g.id}" ${c.sizeClass===g.id?'selected':''}>${g.label} · ${g.range}</option>`).join('')}</select></label><label class="full check-label"><input name="featured" type="checkbox" ${c.featured?'checked':''}>✦ 明星城市 / 作品重要地点</label><label>管辖类型<select name="polityType"><option value="ordinary">普通城市</option><option value="free-city" ${c.polityType==='free-city'?'selected':''}>自由市 ▣</option></select></label><label class="full">所在国家（自由市地理位置；管辖归属由上方所属国家决定）<select name="hostCountryId">${countryOptions(c.hostCountryId)}</select></label><label class="full">英文名称 / 拉丁转写<input name="englishName" maxlength="180" value="${esc(c.englishName||'')}" placeholder="宋国汉语地名使用威妥玛式；民族名称优先原名"></label><label class="full">本地语言名称<input name="localName" dir="auto" maxlength="180" value="${esc(c.localName||'')}"></label><label class="full">本地语言代码<input name="localLanguage" value="${esc(c.localLanguage||'')}" placeholder="zh / bo / mn / ug / ja / …"></label><p class="data-note full">中文名称与真实地点原名分开保存。拼写可直接编辑；地图按“汉 / 英 / 本地”开关显示，重复名称只显示一次。</p>`;$('#modalBody .form-grid').after(box);attachRomanizer(box,c);}
function decorateDetails(entity,isCity){const badge=document.createElement('button');badge.type='button';badge.className='featured-toggle';badge.textContent=entity.featured?'✦ 明星地点':'✦ 标记为明星地点';badge.setAttribute('aria-pressed',!!entity.featured);badge.onclick=()=>transaction('修改明星标记',()=>entity.featured=!entity.featured);$('#details .country-title').after(badge);renderMedia(entity,isCity);const wrapper=document.createElement('section');wrapper.className='socio-block';const d=entity.demographics||{};wrapper.innerHTML=`${isCity?`<p class="data-note">现实对应 / 原型：${esc(entity.realName||'未填写')}</p><div class="names-block"><span>ZH</span><b>${esc(entity.name)}</b><span>EN</span><b>${esc(entity.englishName||'未填写')}</b><span>${esc((entity.localLanguage||'LOCAL').toUpperCase())}</span><b class="native-name" lang="${esc(entity.localLanguage||'und')}" dir="auto">${esc(entity.localName||'未填写')}</b></div>`:''}<div class="detail-subhead"><span>民生与经济</span><button id="editSocio" title="编辑民生数据">✎</button></div><span class="tag pending">${esc(d.kind||'未填写')} · ${esc(d.confidence||'待定')}</span><div class="detail-stats"><div><small>人口 · ${entity.population==null?'未填写':'情景值'}</small><b>${populationText(entity.population)}</b></div><div><small>GDP · 参考美元口径</small><b>${entity.gdp==null?'—':num(entity.gdp)}<span>十亿美元</span></b></div><div><small>人均 GDP</small><b>${entity.population>0&&entity.gdp!=null?num(entity.gdp*1e9/entity.population):'—'}<span>$</span></b></div><div><small>预期寿命</small><b>${entity.lifeExpectancy??'—'}<span>岁</span></b></div><div><small>识字率</small><b>${entity.literacy??'—'}<span>%</span></b></div><div><small>城镇化率</small><b>${entity.urbanization??'—'}<span>%</span></b></div></div><p class="data-note">${esc(d.scenario||'未指定统计年份')}。${esc(d.method||'请填写来源与口径。')}数值可用于创作设定，不代表现实统计或确定预测。</p>`;const anchor=$('#details > .detail-subhead');if(anchor)anchor.before(wrapper);else $('#details').append(wrapper);$('#editSocio').onclick=()=>socioForm(entity);if(isCity){const note=document.createElement('p');note.className='data-note';note.textContent=C.countsInNationalTotals(entity)?'计入国内城市汇总':'不计入国内总数 · 保留本城独立资料';wrapper.prepend(note);}else{const t=C.cityTotals(entity.id,state.territories,state.cities);const summary=document.createElement('section');summary.className='socio-block';summary.innerHTML=`<div class="detail-subhead">已收录城市汇总</div><p>${t.included} 座计入 · ${t.excluded} 座不计入</p><div class="detail-stats"><div><small>城市人口合计</small><b>${populationText(t.population)}</b></div><div><small>城市 GDP 合计</small><b>${num(t.gdp)}<span>十亿美元</span></b></div></div><p class="data-note">含下属地区，按管辖归属统计。未填人口 ${t.missingPopulation} 座，未填 GDP ${t.missingGdp} 座。全国预设包含未收录人口，独立于这份城市合计。</p>`;wrapper.after(summary);}}
function socioForm(entity){enableEditing(true);const d=entity.demographics||{},isCity=state.cities.some(c=>c.id===entity.id);openModal('编辑民生与经济 · '+entity.name,`<div class="form-grid">${isCity?totalsSwitch(entity):''}<label>人口（人）<input name="population" type="number" min="0" step="1" value="${entity.population??''}"></label><label>GDP（十亿美元）<input name="gdp" type="number" min="0" step="any" value="${entity.gdp??''}"></label><label>预期寿命（岁）<input name="lifeExpectancy" type="number" min="0" max="200" step="any" value="${entity.lifeExpectancy??''}"></label><label>识字率（%）<input name="literacy" type="number" min="0" max="100" step="any" value="${entity.literacy??''}"></label><label>城镇化率（%）<input name="urbanization" type="number" min="0" max="100" step="any" value="${entity.urbanization??''}"></label><label>数据性质<select name="kind"><option>创作情景估算</option><option>作者正式设定</option><option>有来源的参考统计</option></select></label><label class="full">年份 / 情景<input name="scenario" value="${esc(d.scenario||'')}"></label><label class="full">口径、来源与估算说明<textarea name="method">${esc(d.method||'')}</textarea></label></div><p class="data-note">人均 GDP 根据人口与 GDP 自动计算。修改国家的数值不会自动改写下属城市。</p>`,data=>{transaction('更新民生数据',()=>{if(isCity)entity.includeInNationalTotals=data.has('includeInNationalTotals');for(const k of ['population','gdp','lifeExpectancy','literacy','urbanization'])entity[k]=data.get(k)===''?null:Number(data.get(k));entity.demographics={...d,kind:data.get('kind'),scenario:data.get('scenario'),method:data.get('method'),confidence:data.get('kind')==='作者正式设定'?'作者确认':'待核定'};});closeModal();});$('#modalForm [name=kind]').value=d.kind||'创作情景估算';}


function renderMedia(entity,isCity){const fields=isCity?[['photo','城市图片'],['historicalPhoto','历史图件']]:[['flag','国旗'],['emblem','国徽']];const section=document.createElement('section');section.className='profile-media '+(isCity?'city-media':'country-media');section.innerHTML=fields.map(([key,label])=>{const m=entity.media?.[key],url=m?.sourceUrl&&/^https:\/\//.test(m.sourceUrl)?m.sourceUrl:null;return `<div><button type="button" class="media-slot ${m?'has-media':''}" data-media="${key}" aria-label="${m?'编辑':'添加'}${label}">${m?`<img loading="lazy" src="${esc(m.dataUrl)}" alt="${esc(m.caption||label)}">`:`<span class="media-placeholder">＋</span>`}<span>${esc(m?.caption||label)}</span></button>${m?.author?`<details class="media-credit"><summary>图片来源</summary><p>${esc(m.author)}${m.license?' · '+esc(m.license):''}${url?` · <a href="${esc(url)}" target="_blank" rel="noreferrer">原图与许可</a>`:''}</p></details>`:''}</div>`;}).join('');const heading=$('#details .country-title');heading.after(section);section.querySelectorAll('[data-media]').forEach(button=>button.onclick=()=>mediaForm(entity,button.dataset.media,fields.find(x=>x[0]===button.dataset.media)[1]));}
function mediaForm(entity,key,label){enableEditing(true);const current=entity.media?.[key];let draft=current?{...current}:null;openModal(label,`<div class="media-preview" id="mediaPreview">${draft?`<img src="${esc(draft.dataUrl)}" alt="${label}">`:'尚未添加图片'}</div><label class="upload-label">选择 PNG / JPEG / WebP 图片<input id="mediaFile" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="form-grid"><label class="full">图片说明<input name="caption" maxlength="250" value="${esc(current?.caption||'')}"></label></div><p class="data-note">单张不超过 4 MB；图片嵌入项目 JSON，导出、导入时一并保存。建议城市图片横向，国旗和国徽使用透明背景或原始比例。</p>${current?'<button type="button" id="removeMedia" class="danger">移除此图片</button>':''}`,data=>{if(!draft){toast('请先选择图片');return;}transaction('保存'+label,()=>{entity.media={...(entity.media||{}),[key]:{...draft,caption:data.get('caption')}};});closeModal();});$('#mediaFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>4*1024*1024){toast('请选择不超过 4 MB 的 PNG / JPEG / WebP 图片');return;}try{const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const image=new Image();image.src=dataUrl;await image.decode();draft={dataUrl,fileName:file.name,caption:'',width:image.naturalWidth,height:image.naturalHeight};$('#mediaPreview').replaceChildren(image);}catch{toast('图片无法读取，请重新选择');}};if($('#removeMedia'))$('#removeMedia').onclick=()=>{transaction('移除'+label,()=>{delete entity.media[key];});closeModal();};}
Promise.all([document.fonts.load('600 15px "Atlas Ming"','宋国随星录'),document.fonts.load('600 15px "Atlas Serif"','Joinanza Москва')]).then(()=>map.draw());
function romanizerMarkup(withName=true){return `<section class="romanizer">${withName?'<label>中文地名<input id="romanZh" value="沪渎"></label>':''}<button type="button" id="romanRead">读取中文发音</button><label>汉语拼音（可改多音字，音节以空格分隔）<input id="romanPinyin" placeholder="hu du"></label><label class="check-label"><input id="romanTones" type="checkbox">保留输入中的声调数字</label><label>威妥玛结果<input id="romanResult" readonly></label><p class="data-note" id="romanNote">离线转换；多音字请核对发音。民族语言名称和历史惯用外文名请保留原名。</p></section>`;}
function bindRomanizer(nameInput){const update=()=>{try{$('#romanResult').value=window.AtlasRomanization.fromPinyin($('#romanPinyin').value,$('#romanTones').checked);$('#romanNote').textContent='核对发音后再应用；不会自动覆盖原有名称。';}catch(e){$('#romanResult').value='';$('#romanNote').textContent=e.message;}};$('#romanRead').onclick=()=>{try{$('#romanPinyin').value=window.AtlasRomanization.chinese(nameInput.value);update();}catch(e){$('#romanNote').textContent=e.message;}};$('#romanPinyin').oninput=update;$('#romanTones').onchange=update;$('#romanRead').click();}
function attachRomanizer(box,c){const section=document.createElement('details');section.className='romanizer-panel';section.innerHTML='<summary>由中文生成威妥玛拼音</summary>'+romanizerMarkup(false)+'<button type="button" id="applyRoman">应用到英文名称</button>';box.after(section);bindRomanizer($('#modalForm [name=name]'));$('#applyRoman').onclick=()=>{const result=$('#romanResult').value;if(!result)return;$('#modalForm [name=englishName]').value=result;toast('已填入英文名称，保存档案后生效');};}
$('#romanizeTool').onclick=()=>{openModal('威妥玛拼音工具',romanizerMarkup(),null,false);bindRomanizer($('#romanZh'));};
$('#showFeatured').onchange=e=>transaction('切换明星标记显示',()=>state.showFeatured=e.target.checked);
$('#populationLegend').innerHTML='<span>城市人口规模</span>'+C.CITY_CLASSES.map(c=>`<span><i style="width:${c.radius*2}px;height:${c.radius*2}px"></i>${c.range}</span>`).join('');
$('#layerWater').onchange=e=>transaction('切换重要水系',()=>{state.showWater=e.target.checked;});
$('#showCountryNames').onchange=e=>transaction('切换国名总开关',()=>{state.showCountryNames=e.target.checked;});
start();

$('#exportImageBtn').onclick=()=>{const views=[['political','政区图'],['standard','常规地图'],['terrain','分层地形'],['contours','等高线'],['nightlights','夜景图'],['reference','原图对照']];openModal('导出地图图片',`<div class="form-grid"><label>地图内容<select name="imageView">${views.map(([v,n])=>`<option value="${v}" ${map.view===v?'selected':''}>${n}</option>`).join('')}</select></label><label>地图形状<select name="imageProjection"><option value="current">当前视角 / 当前形状</option><option value="robinson">平面世界地图</option><option value="globe">地球仪</option><option value="north">北极投影</option><option value="south">南极投影</option></select></label><label>画幅<select name="imageAspect" id="imageAspect"><option value="16:9" selected>横向 16:9</option><option value="3:2">横向 3:2</option><option value="1:1">正方形 1:1</option><option value="current">当前画幅比例</option></select></label><label>图片宽度<select id="resolutionPreset"><option value="1920">1920 px</option><option value="3840" selected>3840 px</option><option value="7680">7680 px</option><option value="custom">自定义</option></select></label><label>宽度（px）<input name="imageWidth" id="imageWidth" type="number" min="640" max="8192" step="1" value="3840" required></label><label>文件格式<select name="imageFormat"><option value="png">PNG</option><option value="jpeg">JPEG</option></select></label><label class="check-label"><input name="transparent" type="checkbox">透明外围背景（PNG）</label></div><p class="data-note" id="exportDimensions"></p><p class="data-note">按所选画幅重新绘制；保留图层、配色、语言和海平面设置。地球仪保持当前朝向，不包含编辑顶点和侧栏。</p><p role="status" id="imageExportStatus"></p>`,async data=>{const button=$('#modalForm button[type=submit]');try{if(button)button.disabled=true;$('#imageExportStatus').textContent='正在绘制高分辨率地图…';const width=Number(data.get('imageWidth')),format=data.get('imageFormat'),projection=data.get('imageProjection');const result=await exportMapImage(map,{width,aspect:data.get("imageAspect"),format,transparent:data.has('transparent'),view:data.get('imageView'),projection:projection==='current'?map.kind:projection,fitWorld:projection!=='current'});const url=URL.createObjectURL(result.blob),a=document.createElement('a');a.href=url;a.download=`随星录-${data.get('imageView')}-${projection==='current'?map.kind:projection}-${state.seaLevel}m-${result.width}x${result.height}.${format==='jpeg'?'jpg':'png'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('#imageExportStatus').textContent=`已导出 ${result.width} × ${result.height} 像素`;}catch(e){$('#imageExportStatus').textContent=e.message;}finally{if(button)button.disabled=false;}});const dims=()=>$('#exportDimensions').textContent=`预计尺寸：${$('#imageWidth').value} × ${Math.round(Number($('#imageWidth').value)/({'16:9':16/9,'3:2':3/2,'1:1':1}[$('#imageAspect').value]||map.w/map.h))} 像素；最高 4000 万像素。`;$('#resolutionPreset').onchange=e=>{if(e.target.value!=='custom')$('#imageWidth').value=e.target.value;dims();};$('#imageWidth').oninput=dims;$('#imageAspect').onchange=dims;dims();};
