import {markerShape} from './city-markers.js';
import {fetchTerrain,validateDemMeta,decodeDemBuffer} from './terrain-loader.js';
import {countryScope,nationalProjection,drawNational} from './country-map.js';
import {placeCityLabel,placeRequiredLabel} from './label-layout.js';
document.fonts.load('600 20px "Atlas Ethiopic"');
const d3=window.d3,C=window.AtlasCore;
export class WorldMap{
 constructor(canvas,callbacks){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.callbacks=callbacks;this.kind='robinson';this.rotation=[-105,-22,0];this.contextPaths={};this.geometryCache=new WeakMap();this.orientationCache=new WeakMap();this.preview=false;this.palette='atlas';this.coastMode='illustrated';this.view='political';this.transform=d3.zoomIdentity;this.paths=[];this.adminPaths=[];this.icePaths=[];this.selected=null;this.hovered=null;this.tool='select';this.drawPoints=[];this.cities=[];this.territories=[];this.layers={territories:true,admin:false,cities:true,ice:false,flood:true,water:true};this.sea=3.7;this.mode='surface';this.terrain=null;this.dem=null;this.customDem=null;this.vertexHandles=[];this.cityHandles=[];this.workerReady=false;this.renderId=0;this.terrainTimer=0;
  this.startTerrainWorker();
  this.zoom=d3.zoom().scaleExtent([.65,2200]).filter(e=>{if(e.type==='wheel')return true;if(this.kind==='globe')return false;return !e.button&&['select','moveCity'].includes(this.tool)&&!this.dragging&&!(this.tool==='moveCity'&&this.cityAt(e.offsetX,e.offsetY));}).on('zoom',e=>{this.transform=e.transform;this.draw();callbacks.zoom?.(e.transform.k);}).on('end',()=>{if(this.kind==='globe'){this.rebuild();this.draw();}this.requestTerrain();});
  d3.select(canvas).call(this.zoom).on('dblclick.zoom',null);
  canvas.addEventListener('pointerdown',e=>this.down(e));canvas.addEventListener('pointermove',e=>this.move(e));canvas.addEventListener('pointerup',e=>this.up(e));canvas.addEventListener('pointercancel',()=>{if(this.dragging)callbacks.cancelEdit?.();this.dragging=null;this.rotating=null;this.preview=false;this.rebuild();this.draw();this.requestTerrain();});
  canvas.addEventListener('dblclick',e=>{if(this.tool==='draw'){e.preventDefault();callbacks.finishDraw?.();}else if(this.tool==='vertices')this.addVertex(e);else if(this.tool==='select'){const c=this.cityAt(e.offsetX,e.offsetY),f=c?this.territories.find(f=>f.properties.id===c.countryId):this.featureAt(e.offsetX,e.offsetY);if(f){e.preventDefault();callbacks.country?.(f);}}});
  canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(this.tool==='vertices'){const h=this.vertexAt(e.offsetX,e.offsetY);if(h)callbacks.removeVertex?.(h.point);}});
  canvas.addEventListener('pointerleave',()=>{callbacks.hover?.(null);});
  new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);
 }
 startTerrainWorker(){
  this.worker=new Worker('terrain-worker.js');this.worker.onmessage=e=>{const m=e.data;if(m.type==='night-ready'){this.nightTextureReady=true;this.requestTerrain();}if(m.type==='ready'){this.workerReady=true;this.requestTerrain();}if(m.type==='rendered'||m.type==='error'){this.terrainBusy=false;if(this.pendingTerrain){const next=this.pendingTerrain;this.pendingTerrain=null;if(next.id===this.renderId){this.terrainBusy=true;this.worker.postMessage(next);}}}if(m.type==='rendered'&&m.id===this.renderId){const c=document.createElement('canvas');c.width=m.width;c.height=m.height;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(m.buffer),m.width,m.height),0,0);this.terrain={canvas:c,transform:m.transform};this.draw();}if(m.type==='error'&&m.id===this.renderId)this.callbacks.error?.('地形计算未完成，请重新选择地图模式。'+m.message);};
  this.worker.onerror=event=>{event.preventDefault();this.worker.terminate();this.workerReady=false;this.terrainBusy=false;this.pendingTerrain=null;this.nightTextureReady=false;this.nightLoading=null;
   if(!this.workerRestarted){this.workerRestarted=true;this.callbacks.status?.('正在重新启动地形计算…');this.startTerrainWorker();if(this.dem)this.worker.postMessage({type:'init',dem:this.dem});if(this.customDem)this.worker.postMessage({type:'custom',dem:this.customDem});if(this.view==='nightlights')this.loadNight().catch(e=>this.callbacks.error?.(e.message));}
   else this.callbacks.error?.('地形计算暂不可用，请刷新页面重试。');
  };
 }
 makeProjection(){if(this.kind==='national'&&this.countryScope)return nationalProjection(this);const compact=this.h<480,top=compact?65:105,bottom=compact?60:64;let p;if(this.kind==='globe')return d3.geoOrthographic().rotate(this.rotation).clipAngle(90).scale(Math.max(60,Math.min(this.w-140,this.h-top-bottom)/2)).translate([this.w/2+15,(this.h+top-bottom)/2]);if(this.kind==='north'||this.kind==='south')p=d3.geoStereographic().rotate([0,this.kind==='north'?-90:90]).clipAngle(90).scale(Math.max(40,Math.min(this.w-90,this.h-top-bottom)/2)).translate([this.w/2,(this.h+top-bottom)/2]);else {p=this.kind==='equirectangular'?d3.geoEquirectangular():d3.geoRobinson();p.rotate([-11,0]).fitExtent([[compact?30:65,top],[this.w-28,this.h-bottom]],{type:'Sphere'});}return p;}
 resize(){const center=this.proj&&this.w&&this.h&&this.transform.k>1.01?this.lonlat(this.w/2,this.h/2):null,oldScale=this.proj?.scale(),oldK=this.transform.k;this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;if(!this.w||!this.h)return;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=this.w*this.dpr;this.canvas.height=this.h*this.dpr;this.proj=this.makeProjection();if(center){const p=this.proj(center),k=oldK*oldScale/this.proj.scale();this.transform=d3.zoomIdentity.translate(this.w/2-p[0]*k,this.h/2-p[1]*k).scale(k);d3.select(this.canvas).property('__zoom',this.transform);this.callbacks.zoom?.(k);}this.rebuild();this.terrain=null;this.draw();this.requestTerrain();}
 d3Geometry(f){if(this.orientationCache.has(f.geometry))return this.orientationCache.get(f.geometry);const v={type:'Feature',properties:{},geometry:C.clone(f.geometry)};const polys=v.geometry.type==='Polygon'?[v.geometry.coordinates]:v.geometry.coordinates;for(const coords of polys){if(d3.geoArea({type:'Polygon',coordinates:coords})>Math.PI*2)for(const r of coords)r.reverse();}this.orientationCache.set(f.geometry,v);return v;}
 displayFeature(f){if(this.kind!=='globe'||(!this.preview&&this.transform.k>=4))return f;let cache=this.geometryCache.get(f.geometry);if(!cache){cache={};this.geometryCache.set(f.geometry,cache);}const key=this.preview?'fast':'normal';if(!cache[key]){try{let base=f.geometry;if(this.preview&&base.type==='MultiPolygon'){const size=p=>{let area=0;const r=p[0];for(let i=0;i<r.length-1;i++)area+=r[i][0]*r[i+1][1]-r[i+1][0]*r[i][1];return Math.abs(area)/2;};const sizes=base.coordinates.map(size),largest=Math.max(...sizes);base={type:'MultiPolygon',coordinates:base.coordinates.filter((p,i)=>sizes[i]>=.08||sizes[i]===largest)};}cache[key]=window.turf.simplify({type:'Feature',properties:{},geometry:base},{tolerance:this.preview?.18:.07,highQuality:false}).geometry;}catch{cache[key]=f.geometry;}}return {type:'Feature',properties:f.properties,geometry:cache[key]};}
 invalidateGeometry(){this.geometryCache=new WeakMap();this.orientationCache=new WeakMap();}
 pathFor(f){try{return new Path2D(d3.geoPath(this.proj)(this.d3Geometry(f))||'');}catch{return new Path2D();}}
 borderFor(f,path){const lines=[];let split=false;for(const ring of C.rings(f)){let line=[];for(let i=0;i<ring.length-1;i++){const a=ring[i],b=ring[i+1],seam=(Math.abs(a[0])>179.999&&Math.abs(b[0])>179.999)||(Math.abs(a[1])>89.999&&Math.abs(b[1])>89.999);if(seam){split=true;if(line.length>1)lines.push(line);line=[];}else {if(!line.length)line.push(a);line.push(b);}}if(line.length>1)lines.push(line);}return split?new Path2D(d3.geoPath(this.proj)({type:'MultiLineString',coordinates:lines})||''):path;}
 entry(f){const display=this.displayFeature(f),path=this.pathFor(display);return {f,path,border:this.borderFor(display,path)};}
 rebuild(){if(!this.proj)return;this.paths=this.territories.map(f=>this.entry(f));this.sphere=new Path2D(d3.geoPath(this.proj)({type:'Sphere'}));if(!this.preview){if(this.admin&&this.layers.admin)this.adminPaths=this.admin.map(f=>({f,path:this.pathFor(this.displayFeature(f))}));if(this.ice&&this.layers.ice)this.icePaths=this.ice.map(f=>({f,path:this.pathFor(this.displayFeature(f))}));if(this.view==='standard')this.rebuildContext();this.rebuildCoast();}this.rebuildWater();this.grid=new Path2D(d3.geoPath(this.proj)(d3.geoGraticule10()));}
 rebuildCoast(){this.coastData=this.coastSets?.get(Number(this.sea.toFixed(2)))||null;if(!this.coastData){this.coastPaths=null;return;}this.coastPaths=this.coastData.features.map(f=>this.pathFor(this.displayFeature(f)));this.coastOutline=this.borderFor(this.displayFeature(this.coastData.features[0]),this.coastPaths[0]);}
 update(territories,cities){this.areas=new Map(territories.map(f=>[f.properties.id,window.turf.area(f)]));this.territories=territories;this.cities=cities;if(this.countryScope)this.countryScope=countryScope(territories,cities,this.countryScope.id);this.rebuildCoast();if(this.proj)this.paths=territories.map(f=>this.entry(f));this.draw();}
 async loadCoast(){const level=Number(this.sea.toFixed(2));if(![3.7,5.03].includes(level))return;this.coastSets??=new Map();this.coastPromises??=new Map();if(!this.coastPromises.has(level))this.coastPromises.set(level,(async()=>{const key=level===3.7?'3_7':'5_03',r=await fetch('data/coast-'+key+'.geojson');if(!r.ok)throw Error('海岸线数据载入失败');this.coastSets.set(level,await r.json());})().catch(e=>{this.coastPromises.delete(level);throw e;}));await this.coastPromises.get(level);this.rebuildCoast();this.draw();}
 async loadDem(){if(this.dem)return this.dem;if(!this.demLoading)this.demLoading=(async()=>{this.callbacks.status?.('正在加载地形高程…');const meta=await fetchTerrain('data/elevation.json',async r=>validateDemMeta(await r.json()));const [surface,bed]=await Promise.all(['surface','bed'].map(kind=>fetchTerrain('data/elevation-'+kind+'.f32',async r=>decodeDemBuffer(await r.arrayBuffer(),meta.width*meta.height))));this.setDem({...meta,surface,bed});return this.dem;})().catch(e=>{this.demLoading=null;throw e;});return this.demLoading;}
 loadReference(){if(this.referenceImages)return;this.referenceImages=['data/reference-current.png','data/reference-regions.png'].map(url=>{const image=new Image();image.onload=()=>this.draw();image.src=url;return image;});}
 needsDem(view=this.view){return ['terrain','contours','nightlights'].includes(view)||(this.layers.flood&&(this.coastMode!=='illustrated'||![0,3.7,5.03].includes(Number(this.sea.toFixed(2)))||this.mode!=='surface'||this.customDem));}
 illustratedCoast(){return this.coastMode==='illustrated'&&[3.7,5.03].some(v=>Math.abs(this.sea-v)<.001)&&!['reference','nightlights'].includes(this.view)&&this.mode==='surface'&&!this.customDem&&!!this.coastData;}
 async loadNight(){if(this.nightTextureReady)return;if(this.nightLoading)return this.nightLoading;this.nightLoading=(async()=>{const image=new Image();image.src='data/nightlights-2016.jpg';await image.decode();const c=document.createElement('canvas');c.width=image.naturalWidth;c.height=image.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,c.width,c.height).data;this.worker.postMessage({type:'night-init',width:c.width,height:c.height,buffer:pixels.buffer},[pixels.buffer]);})().catch(e=>{this.nightLoading=null;throw e;});return this.nightLoading;}
 async loadContext(){if(this.contextData)return;this.contextData=await fetch('data/map-context.geojson').then(r=>{if(!r.ok)throw Error('主要道路与河流载入失败');return r.json();});this.rebuildContext();this.draw();}
 rebuildContext(){if(!this.proj||!this.contextData)return;this.contextPaths={};for(const kind of ['river','road'])this.contextPaths[kind]=new Path2D(d3.geoPath(this.proj)({type:'FeatureCollection',features:this.contextData.features.filter(f=>f.properties.kind===kind)})||'');}
 async loadWater(){if(!this.waterLoading)this.waterLoading=fetch('data/lakes.geojson').then(r=>{if(!r.ok)throw Error('湖泊数据载入失败');return r.json();}).then(data=>{this.waterData=data;this.rebuildWater();this.draw();}).catch(e=>{this.waterLoading=null;throw e;});return this.waterLoading;}
 rebuildWater(){if(!this.proj||!this.waterData)return;this.waterPaths=this.waterData.features.map(f=>({rank:f.properties.rank,path:this.pathFor(this.displayFeature(f))}));this.rebuildContext();}
 setAdmin(features){this.admin=features;this.adminPaths=features.map(f=>({f,path:this.pathFor(f)}));this.draw();}
 setIce(features){this.ice=features;this.icePaths=features.map(f=>({f,path:this.pathFor(f)}));this.draw();}
 setDem(dem){this.dem=dem;this.worker.postMessage({type:'init',dem});}
 setCustomDem(dem){this.customDem=dem?{...dem,values:Float32Array.from(dem.values,v=>v===null?NaN:v)}:null;this.worker.postMessage({type:'custom',dem:this.customDem});this.requestTerrain();}
 elevation(city){const value=C.cityElevation(city,this.customDem,this.dem?{...this.dem,values:this.dem.surface}:null),sample=this.cityElevationSamples?.[city.id];return value.z===null&&sample&&sample.coordinates.every((n,i)=>n===city.coordinates[i])?sample.value:value;}
 requestTerrain(){if(this.coastMode==='illustrated'&&[3.7,5.03].includes(Number(this.sea.toFixed(2)))&&!this.coastSets?.has(Number(this.sea.toFixed(2))))this.loadCoast().catch(e=>this.callbacks.error?.(e.message));if(!this.needsDem()){clearTimeout(this.terrainTimer);this.pendingTerrain=null;++this.renderId;this.terrain=null;return;}if(!this.dem){this.loadDem().catch(e=>this.callbacks.error?.(e.message));return;}clearTimeout(this.terrainTimer);const requestId=++this.renderId;this.terrainTimer=setTimeout(()=>{if(!this.workerReady||!this.proj||!this.w||!this.h||!this.needsDem())return;const scale=Math.min(1,1200/this.w,1200/this.h,Math.sqrt(1000000/(this.w*this.h)));const trans=this.transform,pt=this.proj.translate();const request={type:'render',id:requestId,width:Math.round(this.w*scale),height:Math.round(this.h*scale),projection:{kind:this.kind,rotation:this.kind==='national'?this.nationalRotation:this.rotation,scale:this.proj.scale()*trans.k*scale,translate:[(pt[0]*trans.k+trans.x)*scale,(pt[1]*trans.k+trans.y)*scale]},transform:{x:trans.x,y:trans.y,k:trans.k,ratio:scale},view:this.view,night:!!this.night,mode:this.mode,sea:this.sea,flood:this.layers.flood&&!this.illustratedCoast(),interval:this.interval||500};if(this.terrainBusy)this.pendingTerrain=request;else{this.terrainBusy=true;this.worker.postMessage(request);}},120);}
 setView(view){++this.renderId;this.view=view;if(view==='reference')this.loadReference();if(view==='nightlights')this.loadNight().catch(e=>this.callbacks.error?.(e.message));if(view==='standard')this.loadContext().catch(e=>this.callbacks.error?.(e.message));if(view==='reference'&&this.kind!=='robinson')this.setProjection('robinson');this.terrain=null;this.draw();this.requestTerrain();}
 setProjection(kind){++this.renderId;this.kind=kind;this.transform=d3.zoomIdentity;d3.select(this.canvas).call(this.zoom.transform,d3.zoomIdentity);this.resize();}
 zoomBy(k){d3.select(this.canvas).transition().duration(220).call(this.zoom.scaleBy,k);}
 setCountry(id){d3.select(this.canvas).interrupt();this.countryScope=id?countryScope(this.territories,this.cities,id):null;this.terrain=null;++this.renderId;this.setProjection(id?'national':'robinson');}
 reset(){if(this.countryScope){this.setProjection('national');return;}if(this.kind==='globe'){this.rotation=[-105,-22,0];this.resize();}d3.select(this.canvas).transition().duration(350).call(this.zoom.transform,d3.zoomIdentity);}
 focus(f){if(!this.proj)return;if(this.kind==='globe'){const ll=f.coordinates||f.properties.label||d3.geoCentroid(this.d3Geometry(f));this.rotation=[-ll[0],-ll[1],0];this.setProjection('globe');return;}let p,k;if(f.coordinates){p=this.proj(f.coordinates);k=12;}else {const b=d3.geoPath(this.proj).bounds(this.d3Geometry(f));if(!b.flat().every(Number.isFinite))return;p=[(b[0][0]+b[1][0])/2,(b[0][1]+b[1][1])/2];k=Math.min(30,.7/Math.max((b[1][0]-b[0][0])/this.w,(b[1][1]-b[0][1])/this.h));}d3.select(this.canvas).transition().duration(550).call(this.zoom.transform,d3.zoomIdentity.translate(this.w/2,this.h/2).scale(k).translate(-p[0],-p[1]));}
 screen(p){if(this.kind==='globe'&&d3.geoDistance(p,[-this.rotation[0],-this.rotation[1]])>Math.PI/2)return null;const q=this.proj(p);if(!q)return null;return this.transform.apply(q);}
 lonlat(x,y){if(!this.proj)return null;const q=this.transform.invert([x,y]),p=this.proj.invert(q);if(!p?.every(Number.isFinite)||Math.abs(p[1])>90)return null;const a=this.proj(p);if(!a||Math.hypot(a[0]-q[0],a[1]-q[1])>1)return null;if(this.kind==='north'&&p[1]<0||this.kind==='south'&&p[1]>0)return null;return p;}
 fillColor(f){if(this.view==='nightlights')return '#101c28';if(this.view==='standard')return this.night?'#2a3745':'#f0f3f6';const palettes={atlas:['#82aac7','#dcaaa1','#9cbaa4','#b1a0c8','#d1bf93','#82bdbf','#b99ba8','#a8b5ce'],nordic:['#6e99b4','#a58ea9','#85aaa1','#c3a090','#a9b983','#8490b4','#a4bdc4','#bfb2a5'],contrast:['#5d9bbe','#d1857c','#74ae93','#a28ac2','#c1a862','#5dafa9','#cc97b3','#969dc0'],pastel:['#b3cddd','#e3bbb4','#bfd4ba','#cfc1e1','#ded0ae','#add7d1','#d7b6cc','#c0c9e0']};const palette=palettes[this.palette],index=f.properties.paletteIndex??[...f.properties.id].reduce((a,c)=>a+c.charCodeAt(0),0)%8;const color=palette&&!f.properties.customColor?palette[index%8]:f.properties.color||'#9eb3c2';if(!this.night)return color;const c=d3.hsl(color);c.l=Math.max(.28,c.l*.63);c.s*=.8;return c.formatHex();}
 draw(){if(!this.ctx||!this.proj)return;if(this.countryScope){drawNational(this);return;}const ctx=this.ctx,t=this.transform;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.clearRect(0,0,this.w,this.h);if((this.night||this.view==='nightlights')&&this.kind==='globe')this.drawSpace();ctx.save();ctx.translate(t.x,t.y);ctx.scale(t.k,t.k);ctx.fillStyle=this.view==='nightlights'?'#03080f':this.night?'#132a39':'#c9dfe9';ctx.fill(this.sphere);ctx.strokeStyle='#7f969f';ctx.lineWidth=.7/t.k;ctx.stroke(this.sphere);
  ctx.save();ctx.clip(this.sphere);ctx.strokeStyle=this.night?'#364b5b':'#8ca5ad';ctx.lineWidth=.4/t.k;ctx.setLineDash([2/t.k,4/t.k]);if(!['standard','nightlights'].includes(this.view))ctx.stroke(this.grid);ctx.setLineDash([]);
  const ref=this.referenceImages?.[this.referenceIndex||0];if(this.view==='reference'&&ref?.complete&&this.kind==='robinson'){const r=this.proj.scale()/(2486/Math.PI),tr=this.proj.translate();ctx.drawImage(ref,tr[0]-2573*r,tr[1]-1315.5*r,5146*r,2631*r);}
  if(this.layers.territories&&this.view!=='reference')for(const {f,path,border} of this.paths){if(f.properties.parentId)continue;ctx.fillStyle=this.fillColor(f);ctx.fill(path);ctx.strokeStyle='#778779';ctx.lineWidth=.55/t.k;ctx.stroke(border);}
  ctx.restore();ctx.restore();
  if(this.terrain){const old=this.terrain.transform,ratio=old.ratio,rel=t.k/old.k;ctx.save();ctx.translate(t.x-old.x*rel,t.y-old.y*rel);ctx.scale(rel,rel);ctx.drawImage(this.terrain.canvas,0,0,this.terrain.canvas.width/ratio,this.terrain.canvas.height/ratio);ctx.restore();}
  ctx.save();ctx.translate(t.x,t.y);ctx.scale(t.k,t.k);
  if(['terrain','contours','nightlights'].includes(this.view)&&this.layers.territories){ctx.strokeStyle=this.view==='nightlights'?'#8da6b855':'#5d6755aa';ctx.lineWidth=.65/t.k;for(const {border,f} of this.paths)if(!f.properties.parentId)ctx.stroke(border);}
  if(!this.preview&&this.coastPaths&&this.layers.flood&&this.illustratedCoast()){ctx.fillStyle=this.night?'#132a39':'#c9dfe9';ctx.fill(this.coastPaths[1]);ctx.strokeStyle='#629bb6';ctx.lineWidth=.85/t.k;ctx.stroke(this.coastOutline||this.coastPaths[0]);}
  if(!this.preview&&this.view==='standard'){if(this.layers.water&&this.contextPaths.river){ctx.strokeStyle='#87b9d1';ctx.lineWidth=(t.k>4?1.3:.6)/t.k;ctx.stroke(this.contextPaths.river);}if(t.k>=2&&this.contextPaths.road){ctx.strokeStyle='#dfc58c';ctx.lineWidth=2/t.k;ctx.stroke(this.contextPaths.road);ctx.strokeStyle='#fff9e8';ctx.lineWidth=1/t.k;ctx.stroke(this.contextPaths.road);}}
  if(this.layers.water&&this.view!=='reference'){ctx.save();ctx.clip(this.sphere);ctx.fillStyle=(this.night||this.view==='nightlights')?'#183748':'#bedce9';ctx.strokeStyle=(this.night||this.view==='nightlights')?'#365b70':'#82afc4';ctx.lineWidth=.45/t.k;for(const lake of this.waterPaths||[])if(lake.rank<=(t.k<2?2:t.k<5?3:5)){ctx.fill(lake.path);ctx.stroke(lake.path);}if(this.contextPaths.river&&this.view!=='standard'){ctx.strokeStyle=(this.night||this.view==='nightlights')?'#426b80':'#81b3c9';ctx.lineWidth=(t.k>4?1:.5)/t.k;ctx.stroke(this.contextPaths.river);}ctx.restore();}
  if(!this.preview&&this.layers.ice){ctx.fillStyle='#f5fbfaab';ctx.strokeStyle='#a0babe';ctx.lineWidth=.6/t.k;for(const {path} of this.icePaths){ctx.fill(path);ctx.stroke(path);}}
  if(!this.preview&&this.layers.admin){ctx.strokeStyle='#8b908585';ctx.lineWidth=.45/t.k;for(const {path} of this.adminPaths)ctx.stroke(path);}
  for(const {f,path,border} of this.paths){if(f.properties.parentId&&this.layers.territories){ctx.strokeStyle='#52694aaa';ctx.lineWidth=.8/t.k;ctx.setLineDash([3/t.k,2/t.k]);ctx.stroke(path);ctx.setLineDash([]);}if(f.properties.id===this.hovered&&f.properties.id!==this.selected){ctx.fillStyle='#ffffff35';ctx.fill(path);ctx.strokeStyle='#6d815f';ctx.lineWidth=1.2/t.k;ctx.stroke(border);}if(f.properties.id===this.selected){ctx.save();ctx.shadowColor='#44563c38';ctx.shadowBlur=10/t.k;ctx.fillStyle=this.view==='political'?'#637e471c':'#ffffff15';ctx.fill(path);ctx.shadowBlur=0;ctx.strokeStyle='#4e663e';ctx.lineWidth=1.8/t.k;ctx.stroke(border);ctx.restore();}}
  if(this.adminSelection){ctx.fillStyle='#d7663c55';ctx.strokeStyle='#c35b37';ctx.lineWidth=1.6/t.k;const a=this.adminPaths.find(a=>a.f.id===this.adminSelection.id);if(a){ctx.fill(a.path);ctx.stroke(a.path);}}
  ctx.restore();
  this.labelBoxes=[];if(this.view!=='reference')this.drawLabels();
  if(this.layers.cities)this.drawCities();
  this.drawEditing();
 }
 drawSpace(){const ctx=this.ctx,g=ctx.createRadialGradient(this.w*.35,this.h*.3,0,this.w*.5,this.h*.5,Math.max(this.w,this.h));g.addColorStop(0,'#111f36');g.addColorStop(.5,'#080f1e');g.addColorStop(1,'#030811');ctx.fillStyle=g;ctx.fillRect(0,0,this.w,this.h);let seed=15483;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<Math.min(700,this.w*this.h/1700);i++){const x=rand()*this.w,y=rand()*this.h,r=rand()>.96?1.3:.35+rand()*.45;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=`rgba(210,228,255,${.25+rand()*.65})`;ctx.fill();}}
 drawLabels(){if(this.showCountryNames===false)return;const ctx=this.ctx,t=this.transform,used=this.labelBoxes,langs=this.countryNameLanguages||{zh:true,en:true,local:true};ctx.textAlign='center';ctx.textBaseline='middle';const sorted=this.territories.filter(f=>!f.properties.parentId).sort((a,b)=>(this.areas?.get(b.properties.id)||0)-(this.areas?.get(a.properties.id)||0));for(const f of sorted){const p=f.properties,ll=p.label||d3.geoCentroid(this.d3Geometry(f));if(this.kind==='north'&&ll[1]<0||this.kind==='south'&&ll[1]>0)continue;const q=this.screen(ll);if(!q||q[0]<30||q[0]>this.w-15||q[1]<60||q[1]>this.h-45)continue;const area=this.areas?.get(p.id)||0;if(area<300000e6&&t.k<2)continue;const names=[...new Set([langs.zh?p.name:null,langs.en?(t.k<2&&p.abbreviation?p.abbreviation:p.englishName||p.alias):null,langs.local?p.localName:null].filter(Boolean))];if(this.showFeatured&&p.featured){if(names.length)names[0]='★ '+names[0];else names.push('★');}if(!names.length)continue;const size=area>4000000e6?20:16;ctx.letterSpacing='0.7px';ctx.font=`600 ${size}px "Atlas Serif","Atlas Ming","Atlas Ethiopic","Atlas Syllabics",serif`;const width=Math.max(...names.map(n=>ctx.measureText(n).width))+12,height=names.length*(size+3),box=[q[0]-width/2,q[1]-12,q[0]+width/2,q[1]+height-12];if(used.some(b=>box[0]<b[2]&&box[2]>b[0]&&box[1]<b[3]&&box[3]>b[1]))continue;used.push(box);names.forEach((text,i)=>{const native=text.replace(/^★ /,'')===p.localName,family=native&&p.constructedLanguage?'"Atlas Syllabics",sans-serif':'"Atlas Serif","Atlas Ming","Atlas Ethiopic","Atlas Syllabics",serif';ctx.font=`600 ${i===0?size:native?size:Math.max(11,size-3)}px ${family}`;ctx.strokeStyle=(this.night||this.view==='nightlights')?'#182432de':'#edf3f6c9';ctx.lineWidth=3;ctx.strokeText(text,q[0],q[1]+i*(size+3));ctx.fillStyle=(this.night||this.view==='nightlights')?(i===0?'#edf3fa':'#b7cada'):(i===0?'#263e51':'#60778a');ctx.fillText(text,q[0],q[1]+i*(size+3));});}}
 cityNames(c){const langs=this.nameLanguages||{zh:true,en:true,local:true};return [...new Set([langs.zh?c.name:null,langs.en?c.englishName:null,langs.local?c.localName:null].filter(Boolean))];}
 drawCities(){const ctx=this.ctx,t=this.transform,zoom=t.k*Math.min(this.w/760,this.h/460)*(this.countryScope?5:1);ctx.letterSpacing='0px';this.cityHandles=[];const used=[...(this.labelBoxes||[])];const ordered=[...(this.countryScope?.cities||this.cities)].sort((a,b)=>(b.id===this.selected?1000:0)+(b.labelPriority||0)+(b.capital?10:0)+(b.rank==='metropolis'?3:0)-(a.id===this.selected?1000:0)-(a.labelPriority||0)-(a.capital?10:0)-(a.rank==='metropolis'?3:0)||((b.population||0)-(a.population||0)));for(const c of ordered){if(this.kind==='north'&&c.coordinates[1]<0||this.kind==='south'&&c.coordinates[1]>0)continue;const p=this.screen(c.coordinates);if(!p||p[0]<0||p[0]>this.w||p[1]<0||p[1]>this.h)continue;const elev=this.elevation(c),low=elev.z!==null&&elev.z<this.sea;const forced=this.exportLabelMode==='manual'&&this.exportLabelIds?.has(c.id),selected=c.id===this.selected,display=C.cityDisplay(c,zoom,selected||forced);if(!display.visible)continue;const spacing=zoom<1.5?24:zoom<3?15:8;if(!selected&&!forced&&this.cityHandles.some(h=>Math.hypot(h.p[0]-p[0],h.p[1]-p[1])<spacing))continue;const radius=display.radius,marker=markerShape(c,radius,{simplified:zoom<1.2&&!selected&&!forced}),national=marker.kind==='national',color=low?'#2868c7':national?'#ce4448':(this.night||this.view==='nightlights')?'#dbe7f2':'#4f6b80';ctx.fillStyle=color;ctx.strokeStyle=color;ctx.lineWidth=1;if(marker.filled){ctx.beginPath();ctx.arc(...p,radius,0,Math.PI*2);ctx.fill();}for(const [i,ring] of marker.rings.entries()){ctx.lineWidth=marker.ringWidths[i];ctx.beginPath();ctx.arc(...p,ring,0,Math.PI*2);ctx.stroke();}if(this.showFeatured&&c.featured){ctx.font='600 14px serif';ctx.textAlign='right';ctx.fillStyle='#d5aa63';ctx.fillText('★',p[0]-marker.outerRadius-4,p[1]+3);}this.cityHandles.push({city:c,p});if(this.exportLabelMode==='none'||this.exportLabelMode==='manual'&&!forced||!forced&&!display.label)continue;
 const names=this.cityNames(c);if(!names.length)continue;const labelScale=this.exportLabelScale||1;const fontFor=(name,i)=>{const script=name===c.localName?c.localLanguage:'zh',family=['Inukulaanski','iu'].includes(script)?'"Atlas Syllabics",serif':script==='bo'?'"Microsoft Himalaya",serif':script==='mn'?'"Mongolian Baiti",serif':['ar','ug','fa','kk-Arab'].includes(script)?'"Noto Naskh Arabic",serif':'"Atlas Serif","Atlas Ming","Times New Roman",serif';return `600 ${( ['bo','mn'].includes(script)?17:i===0?13:11)*labelScale}px ${family}`;};ctx.textAlign='left';const width=Math.max(...names.map((n,i)=>{ctx.font=fontFor(n,i);return ctx.measureText(n).width;}))+6,height=names.length*18*labelScale;const placed=((forced||selected)?placeRequiredLabel:placeCityLabel)(p,width,height,used,[this.w,this.h],marker.outerRadius+4);if(!placed)continue;if(placed.overflow)this.labelOverflow=(this.labelOverflow||0)+1;used.push(placed.box);ctx.textBaseline='middle';
 if(placed.leader){ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(Math.max(placed.box[0],Math.min(placed.box[2],p[0])),Math.max(placed.box[1],Math.min(placed.box[3],p[1])));ctx.strokeStyle=this.night?'#91a9bc':'#658298';ctx.lineWidth=.7;ctx.stroke();}
 names.forEach((name,i)=>{ctx.font=fontFor(name,i);ctx.lineWidth=3;ctx.strokeStyle=(this.night||this.view==='nightlights')?'#172635ef':'#edf3f6ed';ctx.strokeText(name,placed.x,placed.y+i*18*labelScale);ctx.fillStyle=low?((this.night||this.view==='nightlights')?'#80b5ff':'#245fb4'):(this.night||this.view==='nightlights')?(i===0?'#edf3fa':'#acbed0'):(i===0?'#263e51':'#637f94');ctx.fillText(name,placed.x,placed.y+i*18*labelScale);});
 }}

 drawEditing(){const ctx=this.ctx;this.vertexHandles=[];if(this.tool==='vertices'){const f=this.territories.find(f=>f.properties.id===this.selected);if(f){const points=C.points(f),used=new Set();for(const point of points){const p=this.screen(point);if(!p||p[0]<65||p[0]>this.w||p[1]<110||p[1]>this.h-45)continue;const key=Math.round(p[0]/9)+','+Math.round(p[1]/9);if(used.has(key))continue;used.add(key);this.vertexHandles.push({point,p});ctx.fillStyle='#fffdf3';ctx.strokeStyle='#d7663c';ctx.lineWidth=1.2;ctx.fillRect(p[0]-2.5,p[1]-2.5,5,5);ctx.strokeRect(p[0]-2.5,p[1]-2.5,5,5);}}}if(this.drawPoints.length){ctx.beginPath();this.drawPoints.forEach((p,i)=>{const q=this.screen(p);i?ctx.lineTo(...q):ctx.moveTo(...q);});ctx.strokeStyle='#ce613c';ctx.lineWidth=2;ctx.stroke();if(this.tool==='draw'){ctx.closePath();ctx.fillStyle='#dc714722';ctx.fill();}for(const p of this.drawPoints){const q=this.screen(p);ctx.fillStyle='#d7663c';ctx.fillRect(q[0]-3,q[1]-3,6,6);}}}
 vertexAt(x,y){return this.vertexHandles.find(h=>Math.hypot(h.p[0]-x,h.p[1]-y)<9);}
 cityAt(x,y){return this.cityHandles.find(h=>Math.hypot(h.p[0]-x,h.p[1]-y)<9)?.city;}
 featureAt(x,y,admin=false){const q=this.transform.invert([x,y]),list=admin?this.adminPaths:this.paths;const ctx=this.ctx;ctx.save();ctx.setTransform(1,0,0,1,0,0);let hit=null;for(let i=list.length-1;i>=0;i--){if((!this.countryScope||this.countryScope.ids.has(list[i].f.properties.id))&&ctx.isPointInPath(list[i].path,...q)){hit=list[i].f;break;}}ctx.restore();return hit;}
 down(e){this.pointerStart=[e.offsetX,e.offsetY];this.moved=false;const ll=this.lonlat(e.offsetX,e.offsetY);if(!ll)return;if(this.kind==='globe'&&this.tool==='select'&&e.button===0){this.rotating={x:e.offsetX,y:e.offsetY,rotation:[...this.rotation]};this.canvas.setPointerCapture(e.pointerId);}if(this.tool==='vertices'){const h=this.vertexAt(e.offsetX,e.offsetY);if(h){e.stopImmediatePropagation();this.callbacks.beginEdit?.();this.dragging={kind:'vertex',point:[...h.point],last:[...h.point]};this.canvas.setPointerCapture(e.pointerId);}}
  if(['city','moveCity'].includes(this.tool)){const city=this.cityAt(e.offsetX,e.offsetY);if(city){e.stopImmediatePropagation();this.callbacks.beginEdit?.();this.dragging={kind:'city',id:city.id};this.canvas.setPointerCapture(e.pointerId);}}}
 move(e){if(this.rotating){++this.renderId;const r=this.rotating,s=55/(this.proj.scale()*this.transform.k);this.rotation=[r.rotation[0]+(e.offsetX-r.x)*s,Math.max(-90,Math.min(90,r.rotation[1]-(e.offsetY-r.y)*s)),0];if(Math.hypot(e.offsetX-r.x,e.offsetY-r.y)>4)this.moved=true;this.preview=true;this.terrain=null;if(!this.rotationFrame)this.rotationFrame=requestAnimationFrame(()=>{this.rotationFrame=null;this.proj.rotate(this.rotation);this.rebuild();this.draw();});return;}if(this.pointerStart&&Math.hypot(this.pointerStart[0]-e.offsetX,this.pointerStart[1]-e.offsetY)>4)this.moved=true;const ll=this.lonlat(e.offsetX,e.offsetY);this.callbacks.coordinates?.(ll);if(this.dragging&&ll){if(this.dragging.kind==='vertex'){this.callbacks.moveVertex?.(this.dragging.last,ll);this.dragging.last=[...ll];}else this.callbacks.moveCity?.(this.dragging.id,ll);this.draw();return;}if(this.tool==='draw'||this.tool==='vertices')return;const city=this.layers.cities?this.cityAt(e.offsetX,e.offsetY):null,f=city||this.featureAt(e.offsetX,e.offsetY,this.tool==='assign');this.hovered=f?.properties?.id||null;this.callbacks.hover?.(f,{x:e.offsetX,y:e.offsetY});this.draw();}
 up(e){if(this.rotating){this.rotating=null;if(this.rotationFrame){cancelAnimationFrame(this.rotationFrame);this.rotationFrame=null;}this.preview=false;this.proj.rotate(this.rotation);this.rebuild();this.draw();this.requestTerrain();}if(this.dragging){this.callbacks.endEdit?.();this.dragging=null;this.pointerStart=null;return;}if(this.moved||!this.pointerStart){this.pointerStart=null;return;}this.pointerStart=null;const ll=this.lonlat(e.offsetX,e.offsetY);if(!ll){if(this.tool==='select')this.callbacks.clear?.();return;}if(this.tool==='draw'){if(e.detail<2)this.drawPoints.push(ll);this.draw();return;}if(this.tool==='city'){this.callbacks.addCity?.(ll);return;}if(this.tool==='moveCity'){this.callbacks.placeCity?.(ll);return;}if(this.tool==='vertices'){const h=this.vertexAt(e.offsetX,e.offsetY);if(h)this.callbacks.vertexSelected?.(h.point);return;}const c=this.layers.cities&&this.cityAt(e.offsetX,e.offsetY);if(c&&this.tool!=='assign'){this.callbacks.select?.(c);return;}const f=this.featureAt(e.offsetX,e.offsetY,this.tool==='assign');if(f){if(this.tool==='assign'){this.adminSelection=f;this.draw();this.callbacks.assign?.(f);}else this.callbacks.select?.(f);}else if(this.tool==='select')this.callbacks.clear?.();}
 addVertex(e){const f=this.territories.find(f=>f.properties.id===this.selected);if(!f)return;let best=null;for(const r of C.rings(f))for(let i=0;i<r.length-1;i++){const a=this.screen(r[i]),b=this.screen(r[i+1]);if(!a||!b)continue;const vx=b[0]-a[0],vy=b[1]-a[1],l=vx*vx+vy*vy,u=l?Math.max(0,Math.min(1,((e.offsetX-a[0])*vx+(e.offsetY-a[1])*vy)/l)):0,p=[a[0]+u*vx,a[1]+u*vy],dist=Math.hypot(e.offsetX-p[0],e.offsetY-p[1]);if(!best||dist<best.dist)best={a:r[i],b:r[i+1],p,dist};}if(best&&best.dist<15)this.callbacks.addVertex?.(best.a,best.b,this.lonlat(...best.p));}
}

