(function(root){
 'use strict';
 // Mandarin syllable conversion; spelling conventions follow the LOC correspondence table.
 // Historic/native names (Lhasa, Edo, etc.) are editorial choices, not Mandarin transliterations.
 const initials={b:'p',p:"p’",m:'m',f:'f',d:'t',t:'t’',n:'n',l:'l',g:'k',k:'k’',h:'h',j:'ch',q:'ch’',x:'hs',zh:'ch',ch:'ch’',sh:'sh',r:'j',z:'ts',c:'ts’',s:'s'};
 const special={zhi:'chih',chi:'ch’ih',shi:'shih',ri:'jih',zi:'tzu',ci:'tz’u',si:'ssu',zii:'tzu',er:'erh',e:'o',yi:'i',ya:'ya',yan:'yen',yang:'yang',yao:'yao',ye:'yeh',yin:'yin',ying:'ying',yong:'yung',you:'yu',yu:'yü',yue:'yüeh',yuan:'yüan',yun:'yün',wu:'wu',wa:'wa',wai:'wai',wan:'wan',wang:'wang',wei:'wei',wen:'wen',weng:'weng',wo:'wo',nue:'nüeh',lue:'lüeh'};
 function syllable(input,tones=false){let raw=input.toLowerCase().replace(/u:/g,'ü').replace(/v/g,'ü'),tone=raw.match(/[1-5]$/)?.[0]||'';raw=raw.replace(/[1-5]$/,'');raw=raw.replace(/[āáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ]/g,c=>{const groups=['āáǎà','ēéěè','īíǐì','ōóǒò','ūúǔù','ǖǘǚǜ'];for(let i=0;i<groups.length;i++){const j=groups[i].indexOf(c);if(j>=0){tone=String(j+1);return ['a','e','i','o','u','ü'][i];}}return c;});
  let out=special[raw];if(!out){const match=raw.match(/^(zh|ch|sh|[bpmfdtnlgkhjqxrzcsyw]?)([a-zü]+)$/);if(!match)throw Error('无法转换音节：'+input);let [,initial,final]=match;if(!['a','ai','an','ang','ao','e','ei','en','eng','ong','i','ia','ian','iang','iao','ie','in','ing','iong','iu','o','ou','u','ua','uai','uan','uang','ui','un','uo','ü','üe','üan','ün'].includes(final))throw Error('请核对音节并用空格分隔：'+input);if(['y','w'].includes(initial))throw Error('请核对拼音音节：'+input);if(!initial){if(!['a','ai','an','ang','ao','o','ou','en','eng'].includes(final))throw Error('请用空格分隔拼音音节：'+input);out=final;}else {if('jqx'.includes(initial)&&final.startsWith('u'))final='ü'+final.slice(1);const finals={e:'o',ie:'ieh',ian:'ien',iong:'iung',ong:'ung',uo:'o',ui:'ui',iu:'iu',un:'un',üe:'üeh'};if(['g','k'].includes(initial)&&final==='ui')final='uei';else if(final==='uo'&&['g','k','h'].includes(initial))final='uo';else final=finals[final]||final;if(['z','c','s'].includes(initial)&&final==='o')out=({z:'tse',c:'ts’e',s:'se'})[initial];else out=initials[initial]+final;}}
  return out+(tones&&tone&&tone!=='5'?tone:'');
 }
 function fromPinyin(text,tones=false){const parts=text.trim().split(/[\s\-’']+/).filter(Boolean);if(!parts.length)return '';return parts.map((p,i)=>{const s=syllable(p,tones);return i===0?s[0].toUpperCase()+s.slice(1):s;}).join('-');}
 function chinese(text){const lib=root.pinyinPro||(typeof require==='function'?require('./vendor/pinyin-pro.js'):null);if(!lib)throw Error('拼音词典尚未载入');if(!/^[\u3400-\u9fff\s·—-]+$/.test(text.trim()))throw Error('请输入中文地名；外文名称请直接编辑');const overrides={'沪渎':'hu du','荥州':'xing zhou','番禺':'pan yu','长安':'chang an'};return overrides[text.trim()]||lib.pinyin(text.trim(),{toneType:'none',type:'array'}).filter(x=>x.trim()).join(' ');}
 const api={syllable,fromPinyin,chinese,convert:text=>fromPinyin(chinese(text))};if(typeof module!=='undefined')module.exports=api;else root.AtlasRomanization=api;
})(typeof window!=='undefined'?window:globalThis);
